- README.md
Noticed that the badge wasn't linked to the twitter page from the README badge.
> Fix link to twitter page

- Cargo.toml
- src/xds.rs
- src/xds/ads_client.rs
- tests/xds.rs
When running `cargo deny` locally I found security advisories for both tokio and prost-types, so bumped them both up to the latest versions in Cargo.toml, and fixed the issues I found along the way.
Work on #327
> Security: Updated tokio + prost-types dependencies

- README.md
I fixed the Twitter badge, but none of the other badges link to appropriate places.
Also `main` doesn't get a CI check, so the `checks` badge was always pending. Replaced it with a badge for docs.rs instead.
> Oops, most of the badges didn't have links

- build/Makefile
- build/README.md
- build/build-image/Dockerfile
This adds `cargo-deny` to `make test`, which also makes sure it is run in Cloud Build for continuous integration.
This found a couple of dependencies that need to be updated because of security advisories. These will be updated in a separate PR.
Closes #327
> Add `cargo-deny` to CI by adding to `make test`

- README.md
- build/templates/release-issue.md
Break out a section on the README.md linking to tagged snapshots of documentation, so that as API changes occur it's still easy to see previous API documentation and accompanying guides. It also stops new users from getting confused by in-flight API changes.
I believe this will aso unblock #293 and also remove the requirement to get a 0.1.0 snapshot for #319, which could block other PRs as well.
> Documentation snapshot/release README.md section

- build/Makefile
- build/README.md
- build/build-image/Dockerfile
Now that we've upgraded to rust 1.54.0, we no longer need to use `+nightly` to run our document tests!
> Remove need for nightly in CI and developer guide

- examples/quilkin-filter-example/src/main.rs
- src/config.rs
- src/config/builder.rs
- src/main.rs
- src/runner.rs
This PR is part of #318, but to make the codebase ready to handle additional subcommands a couple of changes were needed.
This moves the CLI and environment configuration outside of `run`, as we'll need these parts to work in both `test` and `run`, this also makes `run` easier to use in tests, since using it doesn't require arguments or environment to be set.
> Move I/O and configuration out of runner::run

- benches/throughput.rs
- docs/extensions/filters/capture_bytes.md
- docs/extensions/filters/compress.md
- docs/extensions/filters/concatenate_bytes.md
- docs/extensions/filters/debug.md
- docs/extensions/filters/filters.md
- docs/extensions/filters/load_balancer.md
- docs/extensions/filters/local_rate_limit.md
- docs/extensions/filters/token_router.md
- docs/extensions/filters/writing_custom_filters.md
- src/config.rs
- src/lib.rs
- src/main.rs
- src/proxy/builder.rs
- tests/filters.rs
- tests/health.rs
- tests/metrics.rs
- tests/xds.rs
This now makes the `proxy` and `runner` private modules as they don't really provide much for users of the library as the `proxy` and the `runner` could both be considered Quilkin. So their types are now exported at the top-level. So instead of `quilkin::runner::run(…)` it's `quilkin::run(…)` for "running Quilkin", and it's `quilkin::Builder` instead of `quilkin::proxy::Builder`, as you're building a Quilkin server. This is how the top-level docs looks like with these changes.
> Cleanup other parts of the public API.

- .github/workflows/labeler.yml
- .gitignore
I miss this from other projects I work on. I find it makes things easier as a reviewer, as you can quickly identify smaller PRs that require less review and get them reviewed fast, and make sure you block out time for the larger submissions.
I do like the touch with this one that it will ping you a reminder that you might want to split up your PR if you are over 1000 lines 🙂
> GH Action: Sizing labels on PRs

- docs/using.md
- src/cluster/cluster_manager.rs
- src/filters/manager.rs
- src/proxy/server/resource_manager.rs
We don't need to explicitly wait for an update from the xds server during startup since we will eventually get one.
So instead, allow the proxy to startup immediately.
> Remove initial xds update delay

- docs/src/filters/writing_custom_filters.md
- docs/src/proxy-configuration.md
- docs/src/quickstart-agones-xonotic.md
- docs/src/quickstart-netcat.md
- examples/agones-xonotic/README.md
- image/Dockerfile
I missed the change to the file config parameters in PR #350, which broke our development docs as well as our container image builds.
This fixes all that.
> Fix for change: --filename to --config

- README.md
Now that we have our documentation on Github pages, this fixes the links to the development documentation, which otherwise would 404 as the pages no longer exist!
> Fix README.md development documentation links

- tests/compress.rs
- tests/concatenate_bytes.rs
- tests/filter_order.rs
- tests/filters.rs
- tests/health.rs
- tests/load_balancer.rs
- tests/local_rate_limit.rs
- tests/metrics.rs
- tests/no_filter.rs
- tests/token_router.rs
- tests/xds.rs
This removes the `#[cfg(test)] mod tests {}` around the tests in the `tests/` folder, as these tests are only compiled when `cfg(test)` is true. The rest of the diff is reformatting.
> Remove redundant cfg(test)

- docs/src/using.md
"If you require debug output, you can run the same command can be run with the quilkin-debug binary." was a strange sentence.
> Better language on using.md

- src/proxy.rs
- src/proxy/server.rs
- src/proxy/sessions.rs
- src/proxy/sessions/session.rs
- src/proxy/sessions/session_manager.rs
Currently looking at adding some sort of session based state in a filter
and figured to make this a type rather than using a plain tuple of adresses so that
its easier to identify across the repo
> Add a type for session keys

- build/Makefile
- build/build-image/Dockerfile
I had some updates to the documentation I wanted to make, but I wanted to be able to preview the whole documentation set created by `cargo doc` and `mdbook` in the the same directory structure as we have it hosted on Github pages.
Also, I saw #363.
So with some extra components in our build image, and a combination of `cargo watch` and a python dev library that hosts the files, and hot reloads on changes for all documentation, we have a nice local tool for writing and previewing documentation locally!
Closes #365
> `make docs` to preview documentation locally

- build/Makefile
- cloudbuild.yaml
Identifying that we accidentally keep breaking either the release process and/or the released container images since we don't automate testing of it.
So this PR does several things:
* Fix the issues I found in compiling for macos when testing this CI improvement.
* Adds cross compilation into the CI process.
* Add building the image into the CI process.
* Run the Quilkin release and debug images against their default configuration (which does nothing) for a few seconds, to make sure they don't error.
* Increase build image to 32 cores, which keeps the CI build process to ~13 minutes, which is not too bad.
Long term, if we wanted to keep images/binaries temporarily for PR builds, we can also do so.
Work on #318
> CI: Add cross compile and basic image test

- src/main.rs
This removes the `test` command from appearing in the clap output since we will release 0.2 before the test command is ready.
> Remove test subcommand from clap for 0.2

- docs/src/filters/load_balancer.md
- proto/quilkin/extensions/filters/load_balancer/v1alpha1/load_balancer.proto
- src/filters/load_balancer.rs
- src/filters/load_balancer/config.rs
- src/filters/load_balancer/endpoint_chooser.rs
First cut of a hashed load-balancer for Quilkin so all requests from one session go to the same endpoint.
Note that hashes by source IP/port.   Might be good to make it configurable.
Also doesn't implement a consistent hash (so if the set of endpoints changes all flows will re-hash).
> Hash load balancer

- build/Makefile
- examples/quilkin-filter-example/Cargo.toml
- examples/quilkin-filter-example/src/main.rs
Update the custom filter example to the new API surface, and also setup CI so that it ensures that it always compiles against dev Quilkin, and therefore will stay in sync going forward.
Next I want to block out pieces of code and inject them into our docs via mdbook when updating https://googleforgames.github.io/quilkin/main/book/filters/writing_custom_filters.html as well, rather than have them copy pasted.
Work on #373
> Update custom filter example and add CI

- src/runner.rs
we currently only listen for SIGINT while k8s sends
a SIGTERM to shutdown a process, so we need to listen for that
too
> Exit on SIGTERM

- Cargo.toml
- docs/src/proxy-configuration.md
- src/config.rs
- src/proxy/server.rs
If we don't provide a default proxy id this falls back to using the
hostname instead of uuid (and if that fails, then we use a uuid).
For environments like kubernetes, we would like the proxy's id to match
the pod id so that the management server can easily find pod information
for the proxy that is connected to it (the proxy passes its ID when it
connects to the server)
> Use hostname as default proxy id

- docs/src/filters/writing_custom_filters.md
- examples/quilkin-filter-example/build.rs
- examples/quilkin-filter-example/config.yaml
- examples/quilkin-filter-example/src/greet.proto
- examples/quilkin-filter-example/src/main.rs
Updates the custom filter documentation to the latest API changes.
This also includes using mdbook's `include` preprocessor to inject the example code into the documentation.
Note: Because of the use of `include` preprocessor I had to remove the Markdown lists, as they wouldn't format correctly
(See: https://github.com/rust-lang/mdBook/issues/1564).
Closes #373
> Docs: Updated Custom Filters

- Cargo.toml
- docs/src/admin.md
- docs/src/filters/writing_custom_filters.md
- examples/quilkin-filter-example/src/main.rs
- src/config/config_type.rs
- src/filters.rs
- src/filters/capture_bytes.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/concatenate_bytes.rs
- src/filters/debug.rs
- src/filters/factory.rs
- src/filters/load_balancer.rs
- src/filters/local_rate_limit.rs
- src/filters/manager.rs
- src/filters/registry.rs
- src/filters/token_router.rs
- src/proxy.rs
- src/proxy/admin.rs
- src/proxy/config_dump.rs
- src/proxy/server.rs
- src/test_utils.rs
- src/xds/listener.rs
That returns a JSON of the current config the proxy is running with
This includes a breaking change, as the FilterFactory to now needs to return
the config in addition to the filter it created.
Resolves #394
> Add a /config endpoint

- src/filters/capture_bytes/metrics.rs
- src/filters/compress/metrics.rs
- src/filters/local_rate_limit/metrics.rs
- src/filters/token_router/metrics.rs
- src/metrics.rs
Some filter currently call `register` (rather than
`register_if_not_exists`) which throws an error if the metric
has already been registered - this meant that we couldn't use
multiple instances of those filter in the filter chain
> Fix duplicate metric registration for filters

- docs/src/SUMMARY.md
- docs/src/filters.md
>
/kind bug
> /kind hotfix
* Whoops, we missed the ConcatenateBytes filter.
* Fixed broken links on the page.
N/A
N/A
> Fixes for filter documentation

- docs/src/SUMMARY.md
- docs/src/filters.md
- docs/src/filters/firewall.md
- src/filters/firewall.rs
- src/lib.rs
>
> /kind bug
/kind feature
> /kind hotfix
Finishes off the Firewall Filter!
Closes #158
Closes #343
While writing the docs, I found a typo in the name of the Filter, so
included that as well.
> Documentation for Firewall filter

- docs/src/filters/capture_bytes.md
- docs/src/filters/compress.md
- docs/src/filters/concatenate_bytes.md
- docs/src/filters/debug.md
- docs/src/filters/load_balancer.md
- docs/src/filters/local_rate_limit.md
- docs/src/filters/token_router.md
>
> /kind bug
> /kind hotfix
In #432 we introduced having the documentation for a Filter have a openapi spec description, as well as a link to the Rust doc definition of its configuration.
N/A
I liked it so much, I went and did it for the rest of the filters.
> Add "Rust Doc" link to each Filter

- examples/iperf3/run.sh
>
/kind bug
> /kind hotfix
This makes sure the output of the metrics snapshot can be captured by the volume mount when running the container.
N/A
N/A
> Save iperf3 metrics.json in /quilkin

- docs/src/filters.md
- src/filters/chain.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Changes:
* Utilise `histogram_opts` to generate the options for the Histogram to bring the naming inline with other metrics.
* The default Histogram buckets are too large for our usage case. Implemented some exponential buckets based on testing total duration metrics (coming in a later separate PR, for #292).
* Updates the documentation to match.
N/A
N/A
> Align Filter Chain metrics with conventions

- Cargo.toml
- examples/quilkin-filter-example/Cargo.toml
>
> /kind bug
/kind cleanup
> /kind hotfix
Upgraded Tokio and related crates to resolve the security advisory.
https://rustsec.org/advisories/RUSTSEC-2021-0124.html
N/A
Hit me while testing locally, but has yet to hit CI as of yet? Either way, better to get in front of it.
> Upgrade Tokio for RUSTSEC-2021-0124

- image/archive_dependencies.sh
>
/kind bug
> /kind hotfix
If there are ever multiple versions of a dependency in $CARGO_HOME the `archive_dependencies.sh` script would fail.
This fixes this issue.
N/A
N/A
> Fix bug archiving dependencies

- docs/src/faq.md
- docs/src/filters.md
- docs/src/filters/capture_bytes.md
- docs/src/filters/compress.md
- docs/src/filters/token_router.md
- docs/src/proxy.md
- docs/src/quickstart-agones-xonotic.md
- docs/src/using.md
- src/metadata.rs
>
/kind bug
> /kind hotfix
This fixes for all the broken links I found while working on #367.
*Which issue(s) this PR fixes**:
Work on #367
Next PR to close #367 will include automated testing of the documentation, just waiting to see if a bug fix I have in PR will flow through in a timely manner. If not, will install in our build image from my fork while waiting on the fixes.
> Docs: Fix broken links

- xds/cmd/controller.go
/kind bug
Fixes the Kubernetes controller implementation of the xds management server. Without the fix, the controller isn't able to list any `GameServers` or `Pods` in the cluster, and doesn't update connected Quilkin instances with endpoints.
The informer factory only starts informers that were already requested when `Start()` is called. The informers are requested when getting the Lister for a specific type. As we are calling `Lister()` after `Start()`, the informer never watches for the resources, and `List()` will always return the empty list.
> xds-server: Create informers before starting informer factory

- build/Makefile
- build/build-image/Dockerfile
- cloudbuild.yaml
- docs/htmltest.yaml
>
> /kind bug
/kind feature
> /kind hotfix
Introduces both building the documentation sites with `mdbook` and `cargo doc` as well as placing them in the same directory structure as they exist in on GitHub pages.
Utilising `htmltest` to test the links, images, scripts etc in the `mdbook` pages (there are lots of invalid anchors in the rustdoc, so not  testing the links for now - but we could later).
To use locally: `make test-docs` will run the tests for you.
Closes #367
* Had …
> CI: Documentation test gen, links, images, etc.

- macros/Cargo.toml
>
> /kind bug
/kind cleanup
> /kind hotfix
cargo deny can interpret the `license` field, but gets a little confused by the `license-file` since it can't parse the file.
Also crates.io likes it better too, since right now it reports `quilkin-macros` as a non-standard OSS licence.
N/A
N/A
> Fix licence field in macros Cargo.toml

- rust-toolchain.toml
- src/filters/factory.rs
Updates to latest rust, required since `spdx 0.7.0` which is used in `cargo-deny` requires  at least 1.56.1
> Update to Rust 1.57

- xds/README.md
- xds/cmd/controller.go
- xds/cmd/file/file.go
- xds/pkg/snapshot/snapshot.go
- xds/pkg/snapshot/snapshot_test.go
When proxies disconnect this clears their snapshot from
the cache. It periodically checks for snapshots that have
open watches (i.e has a proxy waiting for an update) and
if a snapshot seems idle after a while (the proxy isn't likely
to reconnect) it removes it from the cache.
> xds: delete snapshot for disconnected proxies

- image/archive_dependencies.sh
>
/kind bug
> /kind hotfix
If there are no dependencies utilised that we need to archive source for, this breaks the build process since no dependencies-src.zip file is created, and the Dockerfile has nothing to copy.
This changes the script such that it starts with an empty zip file, and then appends dependencies if and when they exist.
Unblocks #457
If @XAMPPRocky is still on vacation, this will let us merge #457, and I can handle the removal of `slog-json` …
> archive_dependencies.sh: Handle no dependencies

- Cargo.toml
- src/cluster/cluster_manager.rs
- src/endpoint/address.rs
- src/filters/manager.rs
- src/lib.rs
- src/proxy.rs
- src/proxy/admin.rs
- src/proxy/builder.rs
- src/proxy/health.rs
- src/proxy/metrics.rs
- src/proxy/server.rs
- src/proxy/server/resource_manager.rs
- src/proxy/sessions/session.rs
- src/proxy/sessions/session_manager.rs
- src/runner.rs
- src/test_utils.rs
- src/xds/ads_client.rs
- src/xds/cluster.rs
- src/xds/listener.rs
- tests/compress.rs
- tests/filters.rs
- tests/firewall.rs
- tests/metrics.rs
- tests/xds.rs
With the release of https://github.com/tokio-rs/console I wanted to move over to tracing sooner rather than later, so this pulls out all instances of `slog` and replaces them with `tracing`.
resolves #317
> Completely remove `slog` and replace with `tracing`

- src/xds/ads_client.rs
>
/kind bug
> /kind hotfix
Solves the bug where on failure to connect, the retry operation would occur every 500ms.
* Moved the ExponentialBackoff outside the backoff loop, so it didn't get recreated on each retry.
* Reset the backoff back to initial state on the first retry.
* Max the delay at 30s.
* Add jitter of 0-2s to each delay.
Closes #461
Sample log output (slog, edited for clarity), with delay written inline:
```
{"msg":"Unable to connect to the XDS …
```
> Fix exponential backoff on xds client retry

- docs/src/filters/compress.md
>
> /kind bug
> /kind hotfix
Looks like Snappy got rid of their github pages, so the link was 404'ing.
This fixed it!
Unblocks #469 
N/A
> Fix 404 in docs

- xds/README.md
- xds/pkg/cluster/agones/agones.go
- xds/pkg/cluster/cluster.go
- xds/pkg/server/callbacks.go
- xds/pkg/snapshot/snapshot.go
- Adds some new metrics to the management server
- Add metrics to the documentation
- Update documentation to show the kubernetes docs first
since that's the primary binary. Followed by the file
implementation.
> management-server: update metrics and doc

- rust-toolchain.toml
- src/config.rs
- src/config/config_type.rs
- src/endpoint.rs
- src/filters/error.rs
- src/filters/firewall/config.rs
- src/filters/load_balancer.rs
- src/filters/local_rate_limit.rs
- src/filters/token_router.rs
- src/main.rs
- src/metrics.rs
- src/proxy/builder.rs
- src/proxy/config_dump.rs
- src/proxy/server/resource_manager.rs
- src/test_utils.rs
- src/xds/ads_client.rs
- src/xds/cluster.rs
- src/xds/listener.rs
- tests/compress.rs
- tests/filter_order.rs
- tests/xds.rs
This PR updates Quilkin to use 1.58.1, moving some format strings to use the new syntax (`format!("{var}")` instead of `format!("{}", var)`), and removes some more unneeded string parsing for IP addresses that were found while moving to the new syntax.
> Update Rust to 1.58.1

- benches/throughput.rs
>
> /kind bug
/kind feature
> /kind hotfix
Wanted to be able to highlight if we had bottlenecks in performance on read vs write operations on the proxy.
This adds an extra benchmark to throughput.rs called "readwrite" and follows a similar pattern as the overall throughput benchmark, with both direct and proxies traffic utilised as extra comparison values.
Work on #410
This is my first benchmark in Rust - feedback appreciated.
Would be interested if we think the new benchmark …
> Benchmark comparing read and write throughput

- CHANGELOG.md
- Cargo.toml
- README.md
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
Changes for the 0.3.0 release.
Work on #499
N/A
> Release 0.3.0

- Cargo.toml
- src/filters/capture.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/debug.rs
- src/filters/factory.rs
- src/filters/load_balancer.rs
- src/filters/local_rate_limit.rs
- src/filters/manager.rs
- src/filters/match.rs
- src/filters/registry.rs
- src/filters/set.rs
- src/filters/token_router.rs
- src/proxy/builder.rs
- src/proxy/config_dump.rs
- src/proxy/server.rs
- src/proxy/server/resource_manager.rs
- src/runner.rs
- src/test_utils.rs
- src/xds/ads_client.rs
- src/xds/listener.rs
- tests/filters.rs
This PR refactors the state of `FilterRegistry` to being internal to `FilterRegistry` and is now a global append-only and always safe to load (e.g. not blocking) registry of filters. This simplifies some of the state in our code, removing the need for a `FilterRegistry` to be passed down at every level, you can get access to new instances with `FilterRegistry::get` which is available anywhere.
> Refactor FilterRegistry into private static

- .gitmodules
- build.rs
- src/endpoint/address.rs
- src/lib.rs
- src/metadata.rs
- src/xds.rs
- src/xds/ads_client.rs
- src/xds/cluster.rs
- src/xds/listener.rs
- tests/xds.rs
Updates the xDS APIs we use to the latest version of the protobuf APIs, this also removes the redefinition of a lot of these files from the xDS test, and instead makes our definitions in the library public so they can be re-used (but hidden, so this so not be considered a stable or usable API for anyone but our tests.)
> Update xDS APIs

- src/endpoint.rs
- src/endpoint/address.rs
- src/filters/capture/config.rs
- src/filters/compress.rs
- src/filters/compress/config.rs
- src/filters/concatenate_bytes.rs
- src/filters/concatenate_bytes/config.rs
- src/filters/debug.rs
- src/filters/drop.rs
- src/filters/error.rs
- src/filters/firewall.rs
- src/filters/firewall/config.rs
- src/filters/load_balancer.rs
- src/filters/load_balancer/config.rs
- src/filters/local_rate_limit.rs
- src/filters/match.rs
- src/filters/match/config.rs
- src/filters/pass.rs
- src/filters/token_router.rs
- src/metadata.rs
- src/prost.rs
- src/xds/listener.rs
- tests/xds.rs
This splits out most of the type conversion code from #506 in order to make it easier to review and merge.``
> Add conversion to protobuf for most core types

- build/build-image/Dockerfile
>
> /kind bug
/kind cleanup
> /kind hotfix
We just got a new release of htmltest, so we no longer need to build the binary from source.  Shrinks the time to build the build image by quite a bit, as we don't have as much work to do.
N/A
N/A
> Use htmltest binary not build from source

- src/cluster/shared.rs
- src/config.rs
- src/config/config_type.rs
- src/endpoint.rs
- src/filters/capture.rs
- src/filters/compress.rs
- src/filters/debug.rs
- src/filters/factory.rs
- src/filters/token_router.rs
- src/metadata.rs
- src/prost.rs
- src/xds/cluster.rs
- tests/filters.rs
We replaced `serde_yaml` with `serde_json` to simplify writing tests and conversion to protobuf 
https://github.com/googleforgames/quilkin/issues/507
> Replace serde_yaml with serde_json internally

- build/Makefile
- build/build-image/Dockerfile
>
/kind bug
> /kind hotfix
By including a linker for windows and the corresponding toolchain, we can cross compile to Windows quite easily, and then we no longer need cross or Docker in Docker.
(Hopefully) closes #530
@bombsimon if you get a chance to run this on WSL, I'd appreciate it!l
> Remove cross from build tools

- src/proxy/server.rs
- src/proxy/sessions/session.rs
- src/test_utils.rs
- tests/compress.rs
- tests/filters.rs
- tests/firewall.rs
- tests/load_balancer.rs
- tests/local_rate_limit.rs
- tests/no_filter.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
* Remove hardcoded ports, and dynamically assign available ephemeral ports 
* Remove redundancy/consolidate some tests
* Remove unneeded dependency for creating a socket from `TestHelper`
* Add `timeout(...)` everywhere, to avoid test deadlocks on future failures.
* Other small tweaks here and there.
N/A
N/A
> General testing cleanup

- Cargo.toml
- agones/.gitignore
- agones/Cargo.toml
- agones/README.md
- agones/main.tf
- agones/src/lib.rs
- agones/src/pod.rs
- build/Makefile
- build/build-image/Dockerfile
>
> /kind bug
/kind feature
> /kind hotfix
Provides a suite of tools for setting up and running e2e integration tests of Quilkin on Agones.
This includes:
* `agones` module with setup functionality and a simple e2e test
* Convenience terraform script for Agones GKE cluster
* Documentation of setup and usage
* Update build image to include convenience tooling (which is also
eventually needed for integration with CI)
* Make target for running Agones integration tests through the build
image.
Work on #510
**Special …
> Tools for Agones e2e testing

- build/Makefile
>
> /kind bug
/kind cleanup
> /kind hotfix
Makefiles work better with tabbed based spacing everywhere.
I managed to somehow sneak in some spaces, and this cleans all that up!
N/A
N/A
> build/Makefile - convert spaces to tabs

- about.toml
- deny.toml
>
> /kind bug
/kind cleanup
> /kind hotfix
* We no longer ship any MPL licenced content, so removed it, since if we
do encounter it again, it should be included with the image as source.
* We don't have any CC0-1.0 either, so removed it.
* The advisories that we were ignoring, are no longer an issue, so
removed as well.
* No longer using slog-json, so removed that exception.
* Added `Unicode-DFS-2016` as an allowed licence, since `unicode-ident`
is using it in a latest release.
N/A
**Special notes for your …
> Cleanup of licences and advisories

- .dockerignore
- about.toml
- agones/README.md
- agones/main.tf
- agones/src/lib.rs
- build/Makefile
- build/README.md
- build/release/cloudbuild.yaml
>
> /kind bug
/kind feature
> /kind hotfix
This builds out the `build/Makefile` tooling such that you can build, push and test the Quilkin Agones integration against either Minikube or a hosted Kubernetes cluster (tested against GKE + Artifact Registry) in one operation.
Also includes:
* Refactoring such that variable naming across `cargo test` and `make` targets all lined to up to be consistent.
* If `IMAGE_TAG` is not present in `cargo test`, panic.
* Upgrade Agones version in Terraform script.
* Update release cloudbuild.yaml - include an …
> Dev: Build, Push and Test Agones Integrations

- agones/main.tf
- agones/src/lib.rs
- build/Makefile
- cloudbuild.yaml
>
> /kind bug
/kind feature
> /kind hotfix
This makes it such that on each PR, the Agones integration tests are run
against the GKE + Agones cluster specified in ./agones/main.tf
This includes:
* Fix for main.tf to align release branch with Agones version.
* Configure how long to wait before cleaning up past test namespaces.
* Cleanup and optimisation of cloudbuild.yaml.
Work on #510
> Run Agones tests in CI

- src/config/watch/agones/crd.rs
- src/filters/capture.rs
- src/filters/match.rs
- src/filters/token_router.rs
- src/metadata.rs
These just make it easier to see values in the logs, particularly values that are a bag of bytes.
> Use base64 when logging token, add fmt::Display impl for metadata::Value

- Cargo.toml
>
> /kind bug
/kind cleanup
> /kind hotfix
Fixes https://rustsec.org/advisories/RUSTSEC-2020-0159
"Potential segfault in localtime_r invocations"
N/A
Will unblock CI (which doesn't seem blocked yet).
> Fix security advisory in chrono

- src/config/watch/agones/crd.rs
Currently the watch was returning the public IP address with the private port, this fixes that so that it returns the public port instead.
> Use status.ports rather spec.ports with Agones

- src/proxy/server.rs
- src/proxy/sessions/session.rs
- src/utils/debug.rs
This improves the traces from sending and receiving packets to clarify the direction, and also moves `bytes_to_string` to output base64 instead of trying to read the data as a string.
> Clarify packet direction in traces, use base64 for bytes_to_string

- .dockerignore
- build/Makefile
- cloudbuild.yaml
- image/Dockerfile
>
> /kind bug
/kind feature
> /kind hotfix
Several improvements to workflows that flow through the build-image to improve build and iteration times.
This includes:
We don't need this anymore, so no reason to build it for each architecture.
I realised that when mixing the `build-image` workflow with local rust tools, that going between them, they would invalidate each other's incremental cache, since it was fingerprinted on absolute directories - drastically expanding build times between iterations.
Moving to a specific target directory for …
> Improve build-image incremental workflow

- Cargo.toml
- src/xds.rs
- src/xds/client.rs
Currently if the connection terminates mid-stream we don't reconnect, this fixes that.
> Recover xDS connection if stream terminates

- src/xds.rs
- src/xds/client.rs
Previously we only catching stream terminations, but we also want to recover when the underlying tonic connection fails too.
> Catch tonic errors in xDS client loop

- src/main.rs
>
/kind bug
> /kind hotfix
Searching for the config file on every invocation of quilkin is not required.
This is a small optimisation, but also solves the error of #558
(although not the CI issue).
Work on #558
Am looking into how to solve the CI issue seperately.
> Only search for config file when required

- Cargo.toml
- src/config/watch/fs.rs
- src/xds.rs
- src/xds/client.rs
Previously we were reconnecting to the stream, but we weren't resubscribing to resources, so now the stream tracks what resources it's requested in the past and makes fresh discovery requests on reconnect.
> Resubscribe to resources after disconnect, fix test flakiness

- agones/src/lib.rs
- agones/src/sidecar.rs
- src/config/watch.rs
- src/config/watch/agones.rs
- src/config/watch/agones/crd.rs
>
> /kind bug
/kind feature
> /kind hotfix
This integration test only tests that we can create a GameServer in an Agones cluster and connect to it, providing baseline functionality for further integration tests.
This includes making the Agones CRD values public such that they can be accessed from the integration tests.
Work on #510
Found a missing Apache licence header when I was in here, so updated that too.
> Basic Agones GameServer integration test

- agones/src/lib.rs
- agones/src/pod.rs
- agones/src/sidecar.rs
- build/Makefile
>
> /kind bug
/kind feature
> /kind hotfix
Implements an integration test wherein we use Quilkin as a sidecar to an
Agones GameServer container.
Also includes some updates to the test harnesses:
* Function to create a common Quilkin container
* Fixed odd (?) bug where k8s client would sometimes close at the end of tests, failing subsequent other tests.
* Convenience function for grabbing the address of a GameServer so you  can send packets to it.
Work on #510
> Agones GameServer + Quilkin sidecar test

- src/admin.rs
- src/admin/health.rs
- src/proxy.rs
Adds a k8s ready probe endpoint to check when a Quilkin instance is ready to receive traffic, which currently maps to whether it has any endpoints available to forward traffic to.
Closes #590
> Add ready probe endpoint

- src/cluster.rs
- src/config/watch/agones.rs
- src/config/watch/fs.rs
- src/xds.rs
> Add LocalitySet type to ensure there aren't duplicate locality entries

- src/config/watch/agones.rs
This check was wrong and prevents Quilkin from removing stale endpoints unless it gets a restarted event.
> Remove allocated check for deleted gameserver events

- src/metrics.rs
Some metrics were missing the quilkin prefix, this fixes it so that can't happen.
> Fix metrics namespace not always being present

- src/config/watch/agones/crd.rs
When gameservers are deleted, their port is removed. This fixes it so that the gameserver will have a port of zero instead of returning an error.
> Allow gameservers to not have port

- build/ci/github-bot/go.mod
- build/ci/github-bot/go.sum
- build/ci/github-bot/main.go
- cloudbuild.yaml
>
> /kind bug
/kind feature
> /kind hotfix
Added the image artifacts to successful builds.
Since Cloud Build doesn't track pushed images on failure (and the image may/may not exist depending on where it failed) I can only provide directions on how to search for the image after the fact.
Closes #593
Also updated the Go version, and now the CI container registry is public, so one can search for development images.
If you can think of any other improvements, please suggest them!
> Add Build Images to CI results

- cloudbuild.yaml
- docs/src/using.md
- src/cli.rs
- src/config.rs
- src/config/slot.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
This includes several fixes, tweaks and small improvements to #574 that will get it through CI:
* Fix bug in `Slot impl Default` that would cause the default Admin config to be `None`.
* Fix double creation of Admin server
* Return cloudbuild timeout tests for easier CI debugging, and add one for command line config.
* Fixes and small additions to the "using" documentation.
N/A
Sometimes the easiest way to provide feedback is a PR on …
> Fixes for CI failure on `quilkin run #574`

- agones/src/lib.rs
- agones/src/pod.rs
- agones/src/xds.rs
- docs/src/admin.md
- src/admin.rs
- src/proxy.rs
- src/xds/server.rs
>
/kind bug
> /kind hotfix
* Documented /ready
* Fixed bug with /ready with xDS provider, wherein a xDS provider would be marked as not ready if it has no endpoints -- which makes sense for a Proxy, but not for a xDS provider.
* Implemented extra unit and integration tests
Closes #597
> Docs, tests and bug fixes for /ready

- Cargo.toml
- src/config.rs
- src/config/watch/agones.rs
- src/proxy.rs
- src/xds/server.rs
Currently for some reason the management server is not sending back to active clients changes because there is seemingly no receivers. This is a temporary workaround to have the client constantly polling for new changes so that will stay up to date, while we work on addressing the management's bi-directional communication.
This also improves some of the tracing for the xds stream to place relevant information in a span.
> Add short poll to xDS clients as workaround, improve xDS tracing

- src/proxy.rs
This unwrap will fail when the connection fails, instead we ignore the error because we'll retry again in a few milliseconds.
> remove unwrap

- build/Makefile
- build/README.md
- build/build-image/Dockerfile
>
> /kind bug
/kind feature
> /kind hotfix
Using linux/arm64 at the test environment, this implements almost all of getting the build toolchain working on an arm64 host machine.
`make build-macos-binary` is currently not working, but I've left that for later, and documented it as a known issue.
Everything else is working!
Also includes:
* Cleanup unneeded things in build image.
* Updates to linkers used when cross compiling.
* Document known issues with compiling mac binaries.
* Ensure emulation exists where required.
**Which issue(s) this PR …
> (Mostly) Build tools working on arm64

- Cargo.toml
- about.toml
- deny.toml
- docs/src/proxy.md
- image/archive_dependencies.sh
- src/cli.rs
- src/cli/run.rs
- src/config.rs
- src/config/builder.rs
- src/config/slot.rs
- src/lib.rs
- src/main.rs
- src/maxmind_db.rs
- src/proxy.rs
- src/proxy/sessions.rs
- src/proxy/sessions/manager.rs
- src/test_utils.rs
- src/xds/client.rs
- src/xds/server.rs
This adds a Maxmind DB integration so that if you provide quilkin with the source of a maxmind database that matches the structure of IPNetDB, it will output info about the ASN of a new session source.
I also refactored the admin server to be in `cli` to reduce duplication between run and manage.
closes #450
> Add ASN maxmind database integration

- rust-toolchain.toml
- src/filters/load_balancer/endpoint_chooser.rs
- src/proxy.rs
This updates the project to 1.64.0, and takes advantage of the new workspace inheritance to reduce the number of versions of duplicated or different dependencies and project metadata, as well as lines of clippy lints.
> Update to Rust 1.64.0

- examples/agones-xonotic/README.md
>
> /kind bug
/kind cleanup
> /kind hotfix
Just to avoid fragility with updates to examples breaking past release examples, I switched the README on this example to using relative links, so that people didn't end up being directed to pull from main, which will likely break at some point.
Work on #546
N/A
> Sidecar Example README: Switch to relative paths

- src/cli.rs
The way the `admin` flag works will no longer work after #620 so this fixes the style to work in that version. I also noticed we stopped listening to the shutdown signal, so I fixed that.
> Change admin flag to `no-admin`, respect shutdown signal

- src/proxy.rs
- src/xds/server.rs
This is a smaller and better fix for the streams not always being established.
It's still not a full fix which know what issue is (the requests are sent before the stream is ready), and am working on PR for it, but haven't been able to make it pass tests yet.
> Fix not receiving stream pushes

- src/maxmind_db.rs
- src/proxy/sessions.rs
- src/proxy/sessions/metrics.rs
This PR adds ASN and IP prefixes as labels to active sessions so that you can group active connections by ASN entity.
> Added ASN and Prefix labels to active sessions

- agones/src/xds.rs
- docs/src/filters/writing_custom_filters.md
- docs/src/proxy-configuration.md
- examples/agones-xonotic-sidecar/sidecar-compress.yaml
- examples/control-plane.yaml
- examples/iperf3/proxy.yaml
- examples/proxy.yaml
- examples/quilkin-filter-example/config.yaml
- src/cli/manage.rs
- src/cli/run.rs
- src/config.rs
- src/config/builder.rs
- src/main.rs
- src/proxy.rs
- src/xds.rs
- src/xds/client.rs
- src/xds/server.rs
This makes it clear that `port` and `id` can refer a management server's port and id, not just a proxy's. Also added management server's `port` flag.
> Flatten proxy config section into root

- build.rs
- docs/src/filters/timestamp.md
- proto/quilkin/filters/timestamp/v1alpha1/timestamp.proto
- src/filters.rs
- src/filters/error.rs
- src/filters/set.rs
- src/filters/timestamp.rs
- src/lib.rs
- src/metrics.rs
This adds a new timestamp filter that reads in a metadata value as a unix timestamp, and then observes the duration between then and now in a histogram metric that's keyed by the direction and metadata key. This is mainly useful in combination with things like `Capture` which then allows you to parse timestamps from packets.
> Add timestamp filter

- docs/src/filters/writing_custom_filters.md
- examples/quilkin-filter-example/src/main.rs
- src/config/slot.rs
- src/filters.rs
- src/filters/capture.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/concatenate_bytes.rs
- src/filters/debug.rs
- src/filters/drop.rs
- src/filters/firewall.rs
- src/filters/load_balancer.rs
- src/filters/local_rate_limit.rs
- src/filters/match.rs
- src/filters/pass.rs
- src/filters/read.rs
- src/filters/registry.rs
- src/filters/timestamp.rs
- src/filters/token_router.rs
- src/filters/write.rs
- src/proxy.rs
- src/proxy/sessions.rs
- src/test_utils.rs
This moves the filter model from converting `Context`s into `Response` to modifying the context in place. This removes a lot of conversion code in the binary and anecdotally I noticed minor improvements in performance just from using it like this.
> Refactor filter model from Context->Response into ref mut Context

- agones/src/xds.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Added to existing integration test that when a token annotation is removed from a `GameServer` record, it is also removed from the Quilkin endpoint configuration - thereby blocking access to the GameServer.
Closes #589
Getting close to what we need for a 0.4.0 release!
> Agones: Add token removal test.

- src/filters/chain.rs
- src/metrics.rs
- src/proxy.rs
- src/proxy/sessions.rs
- src/proxy/sessions/metrics.rs
This wraps a function around the metric static variables, this is to ensure at compile-time that all metrics always have the correct number of label values, previously there were one or two cases where one label was missing.
> Refactor metrics statics into free fns

- src/cli.rs
- src/cli/generate_config_schema.rs
- src/cli/manage.rs
- src/cli/run.rs
Fixes spurious errors like #626 
fixes #626
> Try to recover when the main process fails

- build/Makefile
- build/darwin-builder/Makefile
- build/darwin-builder/cloudbuild.yaml
>
> /kind bug
/kind feature
> /kind hotfix
While we wait for the darwin-linux image to have official images for arm64, we can host our own, since the work has been done. So this includes cloud build scripts to create the image and host it on the Quilkin repo. We can run this manually for each new Rust version we want to support (takes about 1.5h to run).
So this removes the need for emulation to compile a mac/amd64 binary, on an arm64 host (such as a M1) and sets us up to be able to produce a mac/arm64 binary as well.
**Which issue(s) this PR …
> Build macos binaries on ARM

- Cargo.toml
- src/filters/capture.rs
- src/filters/capture/config.rs
- src/filters/chain.rs
- src/filters/match.rs
- src/filters/match/config.rs
- src/filters/timestamp.rs
- src/filters/token_router.rs
- src/metadata.rs
- src/metadata/symbol.rs
- src/test_utils.rs
This PR adds string interning and symbol resolution for metadata keys, this lowers memory usage for strings, and moves from needing `Arc` to just having a 32 bit id. This also adds support for resolving values to a metadata value in configuration. This allows you to use dynamic metadata values in configuration in places where a static literal is currently allowed.
> Implement string interning and symbol resolution for metadata keys

- docs/src/filters/capture.md
- docs/src/filters/local_rate_limit.md
- docs/src/filters/token_router.md
- examples/grafana-dashboards/dashboards/dashboard-gameservers.yaml
- src/filters/capture/metrics.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/compress/metrics.rs
- src/filters/local_rate_limit/metrics.rs
- src/filters/token_router.rs
- src/filters/token_router/metrics.rs
- src/metrics.rs
- src/proxy.rs
- src/proxy/sessions.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Per https://prometheus.io/docs/practices/naming/#metric-names
"A metric name should have a suffix describing the unit, in plural form Note that an accumulating count has `total` as a suffix, in addition to the unit if applicable."
Therefore, all "packets_dropped" metric names should be "packet_dropped_total".
This implements that change across all packets_dropped metric (which as far as I can tell is the only metric missing this suffix) for both the metric and variable name, which was sometimes …
> Consistency of "packets_dropped_total" metric

- build/Makefile
>
> /kind bug
/kind cleanup
> /kind hotfix
Reusing ~/.cargo in the build started causing issues with permissions and ownership. Moving the registry the build image usages so that there's no collision between local cargo registry and the build image.
N/A
N/A
> Make: Move cargo registry to /target/build-image/

- src/proxy.rs
This was unintentionally not set to trace level, this should save us 6.7% of the time spent based on the metrics.
> Move instrument level to trace

- agones/src/pod.rs
- agones/src/sidecar.rs
- agones/src/xds.rs
- cloudbuild.yaml
- docs/src/admin.md
- docs/src/file-configuration.md
- docs/src/proxy-mode.md
- docs/src/proxy/maxmind.md
- docs/src/quickstarts/netcat.md
- docs/src/xds.md
- examples/agones-xonotic-sidecar/sidecar-compress.yaml
- examples/agones-xonotic-sidecar/sidecar.yaml
- examples/agones-xonotic-xds/README.md
- examples/agones-xonotic-xds/proxy-pool.yaml
- examples/iperf3/run.sh
- src/cli.rs
- src/cli/proxy.rs
This PR changes the name of the run command to `proxy`. I think this makes it more clear what's being *run* than just run itself.
> Rename run command to proxy

- src/xds/client.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Rather than searching for a string in an error message, this creates an Error type for when an xDS endpoint address is invalid.
`http::Uri` will allow some Uri formats that will fail for us, so we also add some extra checks of our own to ensure we have all the information we need to make a connection.
N/A
N/A
> Error for invalid endpoint

- build/Makefile
>
> /kind bug
/kind cleanup
> /kind hotfix
There is no easy / cross platform way to get at the local crate's version, so we are doing some grepping, since we can assume grep is installed on local machines.
This change makes the grep pipeline less brittle by looking for the `name="quilkin"` block first before grepping for the version details.
Unblocks #670
N/A
> Make: package_version less brittle

- docs/preprocessor.sh
- docs/src/proxy-mode.md
>
> /kind bug
> /kind hotfix
Fixed documentation bug with the change from `quilkin run` to `quilkin proxy`
Closes #
Work on #669
> Docs: `quilkin run` vs `proxy` bug in preprocessor

- src/xds/server.rs
This is a simple fix to make debugging #682 easier, at least it should give us a better indication of where the failure is occurring.
> Add warning when watcher fails to send an update

- src/xds/client.rs
- src/xds/server.rs
This is a hot fix for #682, as mentioned, this isn't a complete fix for the issue, but it should be good enough for now to ensure that any updates don't get forgotten, and I think we'll want to keep this implementation of the hotfix in even after we properly fix the issue, as there could be other network issues which this would hopefully solve.
This hot fix is similar to before we're we set the client to repeatedly request new information. The difference between this and the old version, is that this will now only set updates after a set timeout where the proxy hasn't received any new updates, rather than a fixed polling rate, this ensures that there can only be so much drift between a proxy and management server before the proxy starts asking the management server for new information.
> Add hotfix around xDS stream sometimes not responding with changes

- src/xds/server.rs
This pin wasn't needed, this removes an extra heap allocation and needing virtual dispatch.
> Remove unneeded pin requirement

- src/cli/manage.rs
- src/cluster.rs
- src/config.rs
- src/config/watch/agones.rs
- src/config/watch/fs.rs
- src/endpoint.rs
- src/endpoint/locality.rs
- tests/metrics.rs
More #600 work, this adds parameters for setting the `region`, `zone`, and `sub-zone` parameters for control plane services, which are set in clusters that they discover, in the future this will allow the relay to easily shard each control plane's endpoint configuration.
> Add region parameters for control planes

- Cargo.toml
- build.rs
- build/build-image/Dockerfile
- docs/preprocessor.sh
- docs/src/SUMMARY.md
- docs/src/services/relay.md
- proto/quilkin/relay/v1alpha1/relay.proto
- src/admin.rs
- src/cli.rs
- src/cli/manage.rs
- src/cli/proxy.rs
- src/cli/relay.rs
- src/cluster.rs
- src/config.rs
- src/config/watch.rs
- src/config/watch/agones.rs
- src/endpoint/locality.rs
- src/proxy.rs
- src/test_utils.rs
- src/utils/net.rs
- src/xds.rs
- src/xds/client.rs
- src/xds/metrics.rs
- src/xds/server.rs
- tests/metrics.rs
This PR adds the initial implementation of the multi-cluster relay service. This service allows you to connect multiple control planes into a single aDS server for all proxy services.
fixes #600
> Add initial implementation of relay service

- src/cli.rs
- src/cli/manage.rs
- src/config.rs
- src/config/provider.rs
Fixes #697 
This PR addresses the provider task failing, the issue was that we were retrying the spawn, rather than spawning the retry task. This also moves the providers to their own module so that they can be shared between services, for example in #662
> Refactor provider task retrying and move providers to their own module

- src/cli.rs
- src/cli/generate_config_schema.rs
- src/cli/manage.rs
- src/cli/proxy.rs
- src/cli/relay.rs
>
> /kind bug
> /kind hotfix
Closes #
> Add debug line for cli parameters

- src/cli/proxy.rs
Keeps the original xDS client alive until the function completes rather than dropping them after the initial requests.
> Don't drop the stream client until the function completes

- Cargo.toml
- src/cli.rs
- src/cli/manage.rs
- src/cli/proxy.rs
- src/cli/relay.rs
- src/config.rs
- src/config/providers.rs
- src/config/watch/fs.rs
- src/endpoint.rs
- src/filters/chain.rs
- src/lib.rs
- src/xds/client.rs
This PR adds a token routing test except using the relay as the configuration provider for the proxy. This also adds support for file providers to the relay so that the test could be done as a unit test in the library.
> Add test for relay proxy routing (and support for file providers)

- Cargo.toml
- docs/src/services/proxy/filters/writing_custom_filters.md
- examples/quilkin-filter-example/Cargo.toml
- examples/quilkin-filter-example/src/main.rs
- src/config/slot.rs
- src/endpoint/address.rs
- src/filters.rs
- src/filters/capture.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/concatenate_bytes.rs
- src/filters/debug.rs
- src/filters/drop.rs
- src/filters/firewall.rs
- src/filters/load_balancer.rs
- src/filters/local_rate_limit.rs
- src/filters/match.rs
- src/filters/pass.rs
- src/filters/registry.rs
- src/filters/timestamp.rs
- src/filters/token_router.rs
- src/proxy.rs
- src/proxy/sessions.rs
- src/test_utils.rs
This PR switches from using the blocking DNS lookup provided by tokio to `trust-dns-resolver`'s asynchronous resolver. ~~This should resolve #718 however currently it's blocked on either implementing #12, disabling the firewall filter, or changing the firewall logic, as that is the one filter currently that relies on being able to lookup DNS entries in order check them against the firewall.~~
fixes #718
> Resolve DNS asynchronously

- src/config/providers/k8s.rs
Just to make it easier to see what was unknown so it's easier to tell what the server we received was.
> Include debug info on unknown server in warning

- docs/src/services/proxy/filters/writing_custom_filters.md
>
> /kind bug
> /kind hotfix
Looks like https://developers.google.com/protocol-buffers now redirect to https://protobuf.dev/, which (sometimes?) is failing on htmltest.
So fixed the link!
N/A
N/A
> Fix probuf link in docs

- build/Makefile
- docs/src/services/agent.md
- src/cli.rs
- src/cli/agent.rs
- src/cli/proxy.rs
- src/config/providers/k8s.rs
- src/config/providers/k8s/agones.rs
- src/protocol.rs
- src/proxy.rs
- src/utils/net.rs
- tests/qcmp.rs
This PR adds a new service called "Agent", the goal of this service to provide a service more designed for relay setups by only having configuration forwarding rather than also being a management server, and this also has a QCMP service that allows it singable, which will be used in to be able to act as pingable "beacon" as it were in a given cluster.
Following this PR I intend to make a follow-up that removes the `--relay` flag from the management server (as it's not really needed anymore with `agent`), and moves the proxy's QCMP implementation to be its own port using the same task the agent uses to bring those services in line with this one.
> Implement Agent service

- Cargo.toml
- build/templates/github-release.md
- build/templates/release-issue.md
- docs/htmltest.yaml
- docs/src/installation.md
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
* Update versions to 0.7.0-dev
* Small improvements to release process
* Fix some URL testing features / flakiness.
Closes #725
lib.rs is flaky on returning HTTP 200's on link testing - so let's just ignore it. crates.io is the same.
> Prep: 0.7.0-dev

- benches/throughput.rs
- docs/src/services/proxy.md
- docs/src/services/proxy/qcmp.md
- src/cli/proxy.rs
- src/protocol.rs
- src/proxy.rs
- tests/qcmp.rs
This PR moves QCMP onto its own port and worker in the proxy, I initially I thought I needed this, but after I wrote I found a better solution in the client, but I decided to open the PR anyway as makes the implementation cleaner and in theory faster as it avoids allocating on the heap (though I haven't actually measured if this is noticeable). This has the added benefit of allowing operators to choose to disable the protocol by not exposing the port, or allowing operators to have QCMP only instances.
Also I removed the `shutdown_rx` in the downstream workers as that would cause the process to stop accepting packets after it shut down.
> Move QCMP to a seperate port

- Cargo.toml
- agones/Cargo.toml
- agones/src/lib.rs
- agones/src/xds.rs
- src/test_utils.rs
>
> /kind bug
/kind feature
> /kind hotfix
* Finer control over log levels and filters by allowing env filters in a new `enable_log(filter: impl Into<EnvFilter>)` implementation.
* On the `agones` integration side a new `debug_pods(client: &Client, labels: String)` function that will output both the Events and all the logs for any pods that match a given selector.
* Example of use within a currently failing `agones_token_router` agones integration test in PR #712.
Closes #695 …
> Unit and integration test debugging enhancements

- .github/workflows/pr_update.yml
>
> /kind bug
> /kind hotfix
GitHub action that will sequentially update to `main` PRs that pass all their checks and are set to "auto-merge".
Not quite as nice as a merge queue, but at least means you don't have to manually manage a queue of approved PRs.
Work on #737
Stolen from what we do on Agones.
> Automatically update approved PRs with automerge

- agones/src/sidecar.rs
- rust-toolchain.toml
- src/endpoint/locality.rs
- tests/filter_order.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Was about time to update (cargo-deny was complaining), and there is a CVE in cargo, so seemed like the sensible thing to do.
N/A
https://blog.rust-lang.org/2023/08/03/cve-2023-38497.html
> Update to Rust 1.71.1 (cargo CVE-2023-38497)

- Cargo.toml
- src/admin.rs
- src/cli.rs
- src/cli/proxy.rs
- src/cluster.rs
- src/config.rs
- src/config/providers/k8s.rs
- src/config/watch.rs
- src/proxy.rs
- src/test_utils.rs
- src/xds.rs
- src/xds/client.rs
- src/xds/server.rs
This should actually fix the issue with changes not being sent across three services, and removes the constant re-checking for changes by finally fixing the issue with watching clusters. The bug was devilishly subtle, the `Watch` struct watches for changes between two values and sends if they change, however `ClusterMap` had inner `Arc` and thus both the value being held and the value in the channel were always the same.
I also added a `ReadGuard` and split it into `read` and `write` methods, so that's more clear what the intent is.
> Fix watch on clusters, by removing inner Arc

- src/cluster.rs
- src/config.rs
- src/endpoint/locality.rs
This adds logging to the `merge` operation, now that #773 is merged we can add more logs without spamming the logs
> Add logging for what endpoints are added and removed

- Cargo.toml
>
> /kind bug
/kind cleanup
> /kind hotfix
Basically because of this line in 1.30.0 changelog:
> tokio: reduce LLVM code generation
Which should help speed up compile times, and hopefully also reduce memory usage when compiling all the tests 🤞🏻
N/A
N/A
> Update Tokio: 1.32.0

- deny.toml
- src/filters/timestamp.rs
- src/proxy.rs
- src/proxy/sessions.rs
I thought I had already done this, but this moves the upstream socket initialisation to on use rather than in the `Session::new` initialisation. This removes the await point from session creation, preventing session map locking, as such I also removed the `try_get`, and then also removed `SessionArgs` as it was unneeded redirection.
> Late initialise upstream socket to prevent session map lock

- Cargo.toml
- src/cli.rs
/kind feature
this pr adds an option to chose between the following formatting option:
* `auto` - default option, detects if running in an interactive terminal and will choose either "json" or "plain"
* `json` - outputs logs in json
* `plain` - uses default tracing_subscriber output
* `pretty` - uses _tracing_subscriber.pretty()_ output
<details>
<summary>How the options look</summary>
</details>
Closes #531
~Not sure about the naming, "detect" could also be "auto" or if "pretty" should be something like "debug". I am also not sure if the "ppretty" option is needed at all.~
*updated with renamed options*
> add cli option for log formatting (Closes #531)

- src/cli/qcmp.rs
- src/protocol.rs
- src/proxy.rs
- src/proxy/sessions.rs
- tests/qcmp.rs
This is preventing all other PRs from succeeding.
> fix timestamp warnings

- src/cli/proxy.rs
- src/cli/relay.rs
- src/xds.rs
- src/xds/client.rs
- src/xds/server.rs
This PR adds a new flag to both relay and load balancer services.
`--idle-request-interval-secs` adds a timeout for waiting for responses, so that if the service hasn't heard back from a management server in the specified time it will send a request for new resources. This should help catch any spurious errors where a service is unresponsive but the HTTP connection is active, since the request failing will trigger a new HTTP connection.
> Add --idle-request-interval-secs

- .github/workflows/docs.yml
>
/kind bug
> /kind hotfix
In `.github/docs.yaml` we never set `QUILKIN_RELEASE` when an actual release version was being created, so the version of the published docs still had the image hash on it - this fixes that by checking if the Git ref starts with 'v', e.g. v0.7.0, and therefore setting the QUILKIN_RELEASE environment variable.
Work on #786
N/A
> Fix version issue when publishing release docs

- docs/src/services/xds/metrics.md
>
> /kind bug
/kind cleanup
> /kind hotfix
Everywhere else we point to `latest`, so updating this link to do that as well, so this is less likely to happen again.
Unblocks CI.
> Fix broken Envoy link.

- image/Dockerfile
>
> /kind bug
/kind cleanup
> /kind hotfix
Updated base image, which includes a fix to mark the binary as owned by the nonroot user.
Various bits and pieces I'm finding while working through #772
Building the Docker image is working on CI, but without the `--chown=nonroot:nonroot` it refused to work for me locally (permission error), rather odd!
Either way, this updates everything 🤞🏻
> Update to Distroless based on Debian 12

- cloudbuild.yaml
>
> /kind bug
/kind cleanup
> /kind hotfix
I was using Cloud Build to run all the tests for myself, but forgot to add back in this section before committing 🤦🏻‍♂️.
This is me putting it back, so it's back in a public bucket and reachable by everyone.
Fix for https://github.com/googleforgames/quilkin/pull/815#issuecomment-1756157437
Sorry!
> Cloud Build: Put logs back in public bucket

- docs/src/deployment/admin.md
- examples/agones-xonotic-relay/proxy-pool.yaml
- examples/agones-xonotic-relay/relay-control-plane.yaml
- examples/agones-xonotic-xds/proxy-pool.yaml
- examples/agones-xonotic-xds/xds-control-plane.yaml
>
> /kind bug
/kind feature
> /kind hotfix
This adds readiness checks to the xds and relay examples, and updates the liveness checks to be more aggressive than their previous configuration.
Closes #818
Also fixed a small formatting issue in the admin docs (newline between tables).
> Examples: Update readiness and liveness checks.

- benches/throughput.rs
- src/cli.rs
- src/cli/proxy.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/debug.rs
- src/filters/firewall.rs
- src/filters/match.rs
- src/filters/registry.rs
- src/filters/write.rs
- src/proxy.rs
- src/proxy/sessions.rs
- src/test_utils.rs
- src/ttl_map.rs
- src/utils/net.rs
- src/xds.rs
- tests/capture.rs
- tests/compress.rs
- tests/filter_order.rs
- tests/filters.rs
- tests/firewall.rs
- tests/local_rate_limit.rs
- tests/match.rs
- tests/metrics.rs
- tests/no_filter.rs
- tests/token_router.rs
This PR refactors how we handle upstream connections to the gameservers. When profiling quilkin I noticed that there was a lot of time (~10–15%) being spent dropping the upstream socket through its Arc implementation that happened whenever a session was dropped.
As I was thinking about how to solve this problem I also realised there was a second issue, which is that there is a limitation on how many connections Quilkin can hold at once, roughly ~16,383. Because after that we're likely to start encountering port exhaustion from the operating system, since each session is a unique socket.
This brought me to the solution in this PR, which is that while we need to give each connection to the gameserver a unique port, we don't need to give a unique port across gameservers. So I refactored how …
> Refactor sessions to use socket pool

- src/proxy/sessions.rs
- src/ttl_map.rs
The problem was that in dashmap we were occasionally getting unlucky and having sessions sometimes end up in the same shard, which would cause a deadlock since one would be trying to insert into a shard while we still hold a reference to one.
Fortunately this is a pretty simple fix of not returning a reference at all and instead just returning the socket, since that was the only thing that was used out of the session struct.
> Fix dead lock in SessionPool

- src/cli.rs
- src/cli/proxy.rs
- src/cli/proxy/sessions.rs
- src/codec/qcmp.rs
- src/net/xds.rs
This commit makes three changes
* Moves QCMP logs to debug
* Removed the retry function on the command level This is because if it starts failing we'd prefer if k8s restarts it than it restart itself continously.
* Removed the asserts and unwraps in `release_socket`. This was never a problem while running, but could cause issues during teardown when can't rely on how things are being freed.
> Loadtesting fixes

- src/cli/admin.rs
This is to prevent heavy load on the main tasks from saturating the workload and causing the admin server to become unresponsive, then triggering a termination from Kubernetes.
> Move admin server to separate OS thread

- src/cli/proxy.rs
When measured it seems we wasting more time with moving memory into the task than we gained from having it be its own task.
> Remove spawn task for each packet.

- Cargo.toml
- deny.toml
- src/cli.rs
- src/filters/drop.rs
- src/filters/pass.rs
- Remove dirs2 and atty
- Cleanup deny config
- Use std::io::IsTerminal instead of atty
- Fix compile errors when `instrument` feature is enabled
/kind cleanup
Fixes some extremely low hanging fruit after doing a `cargo deny --all-features check` and `cargo clippy --all-features`
> Minor cleanup

- Cargo.toml
- build.rs
- src/net/endpoint/metadata.rs
This was pulling in git2 and writing a lot of data that was never used
in the crate. This just changes build.rs to manually read the HEAD
commit information and set an env var.
AFAICT this is actually superior in every way to built since we no
longer have the extra dependencies, and we actually get up to date
information when the commit changes, which AFAICT was not the case with
built since it was not registering file changes.
> Remove built dependency

- src/cli/proxy.rs
- src/config.rs
- src/config/watch.rs
- src/filters/capture.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/firewall.rs
- src/filters/load_balancer.rs
- src/filters/load_balancer/endpoint_chooser.rs
- src/filters/local_rate_limit.rs
- src/filters/match.rs
- src/filters/read.rs
- src/filters/registry.rs
- src/filters/timestamp.rs
- src/filters/token_router.rs
- src/net/cluster.rs
- src/test.rs
This removes the cloning of endpoints that happens for every packet, which has a large impact when you're talking about 12–20K endpoints.
> Use ClusterMap for Filter::read

- Cargo.lock
- src/filters/capture/affix.rs
- src/pool.rs
- tests/filter_order.rs
Splitting is only done in the capture filter if `remove` is specified, the previous code didn't take into account there could be multiple capture filters, this fixes that oversight and adds an integration and unit test.
> Fix PoolBuffer::split

- Cargo.lock
- Cargo.toml
- benches/compression.rs
- benches/shared.rs
- docs/src/services/proxy/filters/compress.md
- proto/quilkin/filters/compress/v1alpha1/compress.proto
- src/filters/compress.rs
- src/filters/compress/compressor.rs
- src/filters/compress/config.rs
- src/lib.rs
- src/pool.rs
- tests/filter_order.rs
This adds support for LZ4 compression. Initial benchmarks with (seeded) randomized data shows that snappy is easily beating it on both compression and decompression, but thought I might as well PR it.
Resolves: #862
> Add lz4 support

- src/cli/admin.rs
- src/codec/base64.rs
- src/config.rs
- src/config/providers/k8s/agones.rs
- src/config/watch.rs
- src/filters/chain.rs
- src/net/cluster.rs
- src/net/xds.rs
- src/net/xds/client.rs
- src/net/xds/server.rs
- src/test.rs
This just changes `Watch<T>` to no longer require Clone + PartialEq, but rather a `Watchable` trait that can get a marker that can then be compared to the value after the write/read operation to see if it has changed, as right now with the non-incremental xds there is no need to be more granular than that, removing the extremely expensive PartialEq (though it is kept for testing purposes). In addition, this completely removes the clones done on the ClusterMap in favor of just  cloning the Arc<>. All tests pass, but I don't know if there is actually an integration test that really exercises this.
> Remove Watch requirements on Clone/PartialEq

- build.rs
- build/build-image/Dockerfile
>
/kind bug
> /kind hotfix
I noticed on building the release binaries, we were getting the warning:
```
warning: failed to get HEAD path: `git` failed with status exit status: 128
```
Which made me realise that `git` wasn't installed on the build image, and therefore the builds didn't include the git commit.
This implements a fix for this, some better debugging error messaging and also some file ownership issues.
N/A
> Fix: warning: failed to get HEAD path

- src/config/xds.rs
- src/net/xds/server.rs
The initial request, which _should_ be the only `ignore-me` request was being treated as a regular request. Note there is apparently no test that covers this case otherwise the bug wouldn't have been merged
> Send back an empty delta response for initial `ignore-me`

- .github/workflows/ci.yml
- build/Makefile
- cloudbuild.yaml
This allows CI to still check windows/macos compile, but actually run in parallel rather than serializing on each platform and wasting valuable CI time
> Move non-linux builds to github

- build/build-image/Dockerfile
>
/kind bug
> /kind hotfix
Looks like the APT package manage for Google Cloud CLI tools is now enforcing HTTPS access, and the instructions for installation have been updated accordingly.
This fixes the issue wherein you would get
```
502 Bad Gateway [IP: 108.177.127.138 80]
```
When attempting to build the Docker build image from scratch in the past week or so.
N/A
N/A
> Build: Https on packages.cloud.google.com

- build/Makefile
>
> /kind bug
/kind cleanup
> /kind hotfix
Include the licence.html with the released zip file so we declare all dependency licences with our release artifacts in accordance with a few OSS licences.
Closes: #858
N/A
> Add licence.html to release quilkin.zip

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
Updates for the latest release.
Work on #902
Draft release notes are here: https://github.com/googleforgames/quilkin/releases
Please feel free to take a look and/or edit before i submit the release.
> Release 0.8.0

- Cargo.lock
- Cargo.toml
- src/cli/qcmp.rs
- src/codec/qcmp.rs
- src/components/proxy.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/sessions.rs
- src/filters/timestamp.rs
- src/lib.rs
- src/net/phoenix.rs
- src/test.rs
- src/time.rs
- test/src/lib.rs
- tests/qcmp.rs
I made a big mistake in #896 by changing the units of various timestamps from nanoseconds -> seconds, which caused QCMP distances to be completely wrong as the unit change caused all calculations to be 0. This fixes the bug by actually having a modicum of type safety so that all conversions between timestamps and duration/nanoseconds are clear as opposed to "losing" the units. It also changes the `qcmp::ping` test to force a delay and ensure that the calculated time is both less than twice the delay but _also_ greater than the delay, which was why this bug was not detected by the test.
Resolves: #920
> Fix timestamp/duration unit confusion

- src/codec/qcmp.rs
The tests aren't hitting this, but it would be possible for the array to be moved depending on scheduling and potentially cause a segfault
> Fix safety issue

- src/config/providers/k8s.rs
This log isn't that useful because it mostly just pops up as an eventual consistency issue (e.g. we often receive multiple delete events for a server). So it's just noise.
> Make unknown gameserver log debug

- examples/quilkin-filter-example/src/generated.rs
- src/components/admin.rs
- src/components/proxy.rs
- src/main.rs
- src/net.rs
- src/net/phoenix.rs
This fixes the issue where the phoenix HTTP server would stop responding after some amount of time. The issue was that since a single thread was being used for the service, it would deadlock itself accessing the `Inner::nodes` map, as the `background_update_task` could be context switched during an await while a write lock was held, causing the "main" loop to deadlock adding/retrieving nodes (or vice versa). I'm _fairly_ confident this is the fix as now locks will _eventually_ be released as tokio will be driving all tasks, not only a single one.
Resolves: #918 
This also adds thread names to all of the threads and tokio workers spawned by quilkin for easier debug inspection. This also made me realize that because we use `tokio::main` we spawn a ton of extra workers in the proxy case, but …
> Fix phoenix http

- Cargo.lock
- src/codec/qcmp.rs
- src/collections/ttl.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Did a full `cargo update` since rustls has a security issue, but ran into a couple of flaky tests that seem persistent, particularly on Cloud Build - so attempting to do both together.
N/A
> cargo update + flake fixes

- agones/src/lib.rs
- agones/src/sidecar.rs
- src/config/providers/k8s/agones.rs
Upgrading the latest agones, the CRD is out of sync with our version in the Quilkin repo, this PR will solve it.
- First we're just using a version of kube that exposes more information about what is breaking so we can fix it.
Resolves #938
> Upgrade Agones CRD

- src/cli/agent.rs
- src/components/agent.rs
- src/components/manage.rs
- src/config.rs
- src/config/providers.rs
- src/config/providers/k8s.rs
- src/config/providers/k8s/agones.rs
- src/config/watch/agones.rs
- test/src/lib.rs
> Add node address selection via type and ip kind

- deny.toml
Somehow the previous PR got in without this commit, so this fixes the deny check failure.
> Add kube@0.91 to skip-tree

- agones/README.md
- agones/main.tf
- agones/src/relay.rs
- docs/src/deployment/quickstarts/agones-xonotic-relay.md
- docs/src/deployment/quickstarts/agones-xonotic-xds.md
- src/config/providers/k8s/agones.rs
>
> /kind bug
/kind feature
> /kind hotfix
* Updated Agones to 1.40.0 with our test infrastructure.
* Some spelling fixes.
* Allow null ports and address fields in GameServer CRD (thanks @XAMPPRocky)
N/A
Content of #942 included.
> Upgrade Agones to 1.40.0 + CRD changes

- src/cli.rs
- src/cli/agent.rs
- src/components/admin.rs
- src/components/agent.rs
- src/components/manage.rs
- src/net/xds/client.rs
This wasn't an intuitive reset, and led to confusion, so removing for now
Resolves #861
> Remove idle request interval for agent

- docs/src/services/proxy/filters/writing_custom_filters.md
- src/cli.rs
- src/codec/qcmp.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/sessions.rs
- src/net.rs
The changes with regard to tracing spans and uring_spawn! are due to tracing_subscriber's use of shared_slab, which has a default limit of [4096 threads](https://github.com/hawkw/sharded-slab/blob/ee45b4cfa79408fc46893a67f2d3005f79e4e04c/src/cfg.rs#L140) after which it will panic. This just changes it so that spans are not present in release mode which is unfortunate, but means that we won't get panics at runtime when "too many" unique connections are made to a proxy.
Other than that, the change was fairly simple, when the senders are closed, and thus the receiver will never get anything again, we exit the loop/task. In addition, when the downstream loop is closed, we also exit the upstream loop, as previously the loop would have just sat there infinitely until shutdown, taking system …
> Fix infinite loop

- src/components/agent.rs
- src/components/manage.rs
- src/components/relay.rs
- src/config/providers.rs
- src/config/watch/agones.rs
> Ignore config maps for agents

- crates/test/src/lib.rs
- crates/test/tests/mesh.rs
- crates/test/tests/proxy.rs
- crates/xds/src/client.rs
- crates/xds/src/config.rs
- crates/xds/src/lib.rs
- crates/xds/src/resource.rs
- crates/xds/src/server.rs
- src/cli/proxy.rs
- src/components/manage.rs
- src/components/proxy.rs
- src/components/relay.rs
- src/config.rs
- src/config/slot.rs
- src/config/watch/fs.rs
- src/filters.rs
- src/filters/token_router.rs
- src/test.rs
This was caused by `config.filters` being a `Slot<>`, which only allows one closure at a time to be notified when the value changes. The relay creates both a relay and management service, which both subscribed to changes, meaning the management closure was dropped and replaced by the relay one, which meant the delta stream would never send updates for filters unless the client did a refresh if the interval was surpassed.
Resolves: #960
> Fix relay listener updates

- docs/preprocessor.sh
- docs/src/services/xds/providers/agones.md
- docs/src/services/xds/providers/filesystem.md
>
> /kind bug
/kind cleanup
> /kind hotfix
Adding the `--help` output for each provider to the guide for each managed provider.
This just ensures we always have up-to-date command docs for each provider.
N/A
Was more useful when we had some more args, but I've been wanting to do this for a while, just to make sure if new options show up they are always documented immeadiately.
> Guide: Show command options for `manage providers`

- src/filters/token_router.rs
- src/net/cluster.rs
> Build single token -> address map

- src/components/proxy.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/sessions.rs
- src/components/proxy/sessions/inner_metrics.rs
- src/metrics.rs
- src/net/maxmind_db.rs
I noticed this while doing a different change so split this out since it was unrelated but didn't want to forget it.
Basically, the `IpNetEntry` has been drastically slimmed down to only deserialize/allocate the fields that are actually used, and additionally added a `MetricsIpNetEntry` which is even further slimmed down to the only 2 fields that are used in _all_ of the metrics _except_ for the session counter. Additionally we use metrics::AsnInfo to just have a stack buffer with the stringized ASN which avoids several heap allocations in places where packets are sent/received and emit multiple metrics.
This should get rid of several m/billion allocations over the lifecycle of a proxy
> Reduce ASN related allocations

- crates/gen.rs
- crates/proto-gen/gen.rs
- crates/test/src/lib.rs
- crates/test/tests/mesh.rs
- crates/test/tests/proxy.rs
- crates/xds/src/server.rs
- src/cli/proxy.rs
- src/components/proxy.rs
- src/components/proxy/error.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/sessions.rs
- src/filters/capture.rs
- src/filters/compress.rs
- src/filters/drop.rs
- src/filters/error.rs
- src/filters/firewall.rs
- src/filters/local_rate_limit.rs
- src/filters/match.rs
- src/filters/registry.rs
- src/filters/token_router.rs
- src/net.rs
- src/test.rs
This is a rework of #986
This resolves an unbounded memory growth issue that can occur in a particularly hostile context, ie, every packet is invalid in some way, generating an error, and CPU usage is high enough that tasks, notably
https://github.com/googleforgames/quilkin/blob/50d91e4167f9160c5be36178e47789fb7844dfc1/src/components/proxy/packet_router.rs#L272-L295
do not consistently receive CPU time. In this context, where every received packet generates an error, which is then sent to an unbounded channel before being dequeued, the dequeue task might not run quickly enough to dequeue each error, causing both the memory allocated by the error, as well as by the queue, grow quickly enough that the process can be OOM killed.
This PR changes it so that instead of each error being sent to …
> Cap error heap usage

- README.md
> Update project to beta status

- build/Makefile
- cloudbuild.yaml
>
> /kind bug
/kind cleanup
Just being explicit, not implicit with container caching.
Just a bit of cleanup
N/A
Checking if cloudbuild still caches as expected before moving to full PR.
> Build: More explicit container caching

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- build/templates/release-issue.md
- crates/macros/Cargo.toml
>
> /kind bug
/kind release
* Changes for upcoming release
* Small tweaks to the release process
Work on #964
Release note draft at: https://github.com/googleforgames/quilkin/releases
> Release 0.9.0

- tests/token_router.rs
>
> /kind bug
/kind cleanup
This is an integration test to ensure that concurrent clients to the same proxy and endpoint didn't mix packets. Could not replicate the reported issue below, but it felt like a good test to have for concurrency testing.
Work on #988
N/A
> Test: Concurrent clients for TokenRouter

- src/cli/proxy.rs
If you use either you currently get this error at runtime.
```
thread 'main' panicked at /home/ep/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.13/src/builder/debug_asserts.rs:112:17:
Command proxy: Short option names must be unique for each argument, but '-t' is in use by both 'to' and 'to_tokens'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> Remove short args for --to and --to_tokens because they conflict

- src/codec/qcmp.rs
This just uses the simple epoll QCMP loop for linux, io_uring gives no benefits as we are only ever doing a single recv or send request at a time. For now it just spawns a task on the main tokio runtime, so in high CPU usage scenarios this will affect the timing, but...that might be a good thing? Unsure.
> Just use epoll for qcmp

- src/components/proxy/io_uring_shared.rs
I spent some time trying to repro #1019 but was unable to, in a non-k8s context. AFAICT there is no segfault or the like introduced in the io-uring refactor that would result in a failure, and that it's most likely just the normal pod lifecycle where a `SIGTERM` was sent to shutdown the pod, but it resulted in errors instead of gracefully shutting down. This code just ignores the submit_and_wait syscall failing due to an interrupt, which actually more closely matches what tokio-uring does.
https://github.com/tokio-rs/tokio-uring/blob/7761222aa7f4bd48c559ca82e9535d47aac96d53/src/runtime/driver/mod.rs#L70C58-L71
Resolves: #1019
> Ignore submit_and_wait failing if it is interrupted

- src/codec/qcmp.rs
- src/components/proxy/sessions.rs
- src/net.rs
- src/net/phoenix.rs
- src/test.rs
- tests/capture.rs
- tests/compress.rs
- tests/concatenate.rs
- tests/filter_order.rs
- tests/filters.rs
- tests/firewall.rs
- tests/load_balancer.rs
- tests/local_rate_limit.rs
- tests/match.rs
- tests/metrics.rs
- tests/no_filter.rs
- tests/qcmp.rs
- tests/token_router.rs
This adds an ignore for tests that currently fail on macOS, these should eventually be fixed but for now it's better to ignore them to allow for dev of other stuff to work on Mac natively.
> Ignore failing tests on macOS

- docs/src/services/proxy/metrics.md
This PR improves documentation
> improvement: add note about measure units of jitter metric

- .cargo/config.toml
- Cargo.lock
- benches/token_router.rs
- src/components/proxy/io_uring_shared.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/packet_router/io_uring.rs
- src/components/proxy/packet_router/reference.rs
- src/config/slot.rs
- src/filters.rs
- src/filters/capture.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/concatenate.rs
- src/filters/debug.rs
- src/filters/drop.rs
- src/filters/firewall.rs
- src/filters/load_balancer.rs
- src/filters/load_balancer/endpoint_chooser.rs
- src/filters/local_rate_limit.rs
- src/filters/match.rs
- src/filters/pass.rs
- src/filters/read.rs
- src/filters/registry.rs
- src/filters/timestamp.rs
- src/filters/token_router.rs
- src/net/cluster.rs
- src/test.rs
This removes the unnecessary heap allocation for the destination address(es) for downstream packets by just making it a mutable reference that is passed from the packet router driver.
> Remove destination address allocation

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/test/Cargo.toml
- crates/test/tests/proxy.rs
- src/collections/ttl.rs
- src/components/proxy.rs
- src/components/proxy/io_uring_shared.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/packet_router/io_uring.rs
- src/components/proxy/packet_router/reference.rs
- src/components/proxy/sessions.rs
- src/components/proxy/sessions/io_uring.rs
- src/components/proxy/sessions/reference.rs
This makes it so that enqueuing buffers to be sent is now done with `PendingSends` for both io-uring and tokio implementations. This means io-uring no longer needs its own tokio runtime just to drive the channel futures to transition back to sync code. Instead of a single downstream channel that can be picked up by any receiver, the sessionpool now just has a vector of pending sends that it round robins between to spread out downstream sends.
Since I wanted to remove the tokio runtime from the io-uring thread, this also meant I needed to figure out a way to get rid of the shutdown receiver that was also async, so since all loops have a `PendingSends` now, I just made it so that you can signal the thread that is the receiver for the pending sends to shutdown, consolidating things a bit.
> Remove async channels for pushing buffers to be sent

- src/net/phoenix.rs
This makes the more noisy one debug for now, and elevates one that is probably actually indicative of underlying issues an error.
> chore: update phoenix log levels

- docs/src/deployment/admin.md
- docs/src/services/proxy/metrics.md
- docs/src/services/proxy/qcmp.md
>
> /kind bug
Documentation for new metrics introduced in #1047
N/A
N/A
> Docs for new metrics (shutdown, qcmp, etc)

- src/components/proxy/io_uring_shared.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/packet_router/reference.rs
- src/components/proxy/sessions.rs
- src/config/slot.rs
- src/filters.rs
- src/filters/capture.rs
- src/filters/chain.rs
- src/filters/compress.rs
- src/filters/compress/compressor.rs
- src/filters/concatenate.rs
- src/filters/debug.rs
- src/filters/drop.rs
- src/filters/firewall.rs
- src/filters/load_balancer.rs
- src/filters/local_rate_limit.rs
- src/filters/match.rs
- src/filters/pass.rs
- src/filters/read.rs
- src/filters/registry.rs
- src/filters/timestamp.rs
- src/filters/token_router.rs
- src/filters/write.rs
- src/pool.rs
- src/test.rs
This moves the DownstreamPacket struct to be completely sans-IO, meaning it is now generic over any input container and output container. This is just a basic shell right now to enable building and testing more stuff without IO, and to enable alternatives like XDP to integrate easily.
> refactor: Make DownstreamPacket sans-io

- crates/test/tests/proxy.rs
- src/components/proxy.rs
- src/components/proxy/error.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/packet_router/io_uring.rs
- src/components/proxy/packet_router/reference.rs
- src/net/io_uring.rs
This isn't as needed anymore, and creates a lot of noise in the logs. I think we could maybe bring the info back under a HTTP endpoint, but for now we can pull this part out.
> refactor: Remove pipeline logging

- Cargo.lock
- crates/test/src/lib.rs
- crates/xdp/src/lib.rs
- src/cli/proxy.rs
- src/components/proxy.rs
- src/net/xdp.rs
- src/test.rs
This adds the support for several XDP specific options, and the initialization code to bring up the XDP I/O loop, falling back to io-uring if setup fails for some reason. This PR _always_ falls back to io-uring at the moment, this is just to get the code in so that it can be iterated on in further PRs, as I only tested that we can spinup quilkin proxy using XDP and shut it down cleanly, not the actual I/O which I'm leaving for tomorrow.
Fixed several bugs:
- Fix bug in ephemeral port range parsing
- Remove warning about eBPF logging, the current eBPF program has no log messages, which makes log initialization fail, but we would want to enable it in the future if we did add logging to the program
- `pthread_cancel` is apparently super not good and was causing a crash at shutdown due to …
> Add XDP CLI options and initialization code

- src/components/proxy.rs
This allows to explicitly enable it if the force flag is on, otherwise the force flag just disables the whole proxy and I'd like the ability to test it at runtime, so it's easy to test deployed images.
> feat: Allow XDP when force flag is set

- src/components/agent.rs
- src/config.rs
- src/config/providersv2.rs
- src/config/watch/agones.rs
This just replaces the functionality for agent for now, to allow it to be merged without breaking and updating the rest in separate PRs.
> refactor: Add new providers struct, and use it for agents

- src/cli/service.rs
This actually bubbles up service initialization errors rather than silently swallowing them, leaving them in an unknown state.
> Allow service initialization to fail

- src/config.rs
- src/net/phoenix.rs
`ResourceType::Datacenter` was not actually handling removed resources, and the `Phoenix::add_nodes_from_config` was only ever adding nodes, never removing them.
Resolves: #1036
> Remove datacenters from phoenix

- crates/xds/src/client.rs
- crates/xds/src/config.rs
This is purely a guess about one thing that could go wrong if a proxy needs to connect to a new relay.
> Fully refresh local state on new connection

- build/Makefile
- build/build-image/Dockerfile
- cloudbuild.yaml
I'm pretty sure all of this functionality is already tested in GHA, so just remove it for now for faster release image builds.
> chore: Remove parts of GCB that are covered by GHA

- Cargo.lock
- Cargo.toml
- crates/test/src/lib.rs
- src/cli.rs
- src/cli/agent.rs
- src/cli/proxy.rs
- src/cli/service.rs
- src/components/admin.rs
- src/components/agent.rs
- src/components/manage.rs
- src/components/proxy.rs
- src/config.rs
- src/config/providers/k8s.rs
- src/config/providersv2.rs
- src/config/serialization.rs
- src/config/watch/agones.rs
- src/config/watch/fs.rs
- src/metrics.rs
- src/net/phoenix.rs
- Adds `DynamicConfig` as a field of `Config`
- Moves `id` and `version` to `DynamicConfig`
- Change phoenix and k8s to only take the fields they actually need instead of an entire config
- Change admin to only take in a `<C: Serialize>` as it only cares about dumping the config as JSON
Part of #1117
> Begin config migration

- Cargo.lock
- crates/xds/Cargo.toml
- crates/xds/src/config.rs
- crates/xds/src/server.rs
- src/config.rs
Currently we take the host value, but that might not match if the service is behind a HTTP proxy, so we parse the standard (and common non-standard) headers to get this information.
> feat: parse origin IP through proxy headers

- src/net/xdp.rs
- src/net/xdp/process.rs
> Ignore normal errors

- docs/src/services/proxy/qcmp.md
- src/codec/qcmp.rs
- src/metrics.rs
* `quilkin_service_qcmp_active`
Whether the QCMP service is currently running, either 1 for running or 0 for not.
* `quilkin_service_qcmp_bytes_total{kind}`
Total number of bytes processed through QCMP. `kind` is either `valid`, `invalid`, or `unsupported`.
* `quilkin_service_qcmp_errors_total`
Total number of errors QCMP has encountered.
* `quilkin_service_qcmp_packets_total{kind}`
Total number of packets processed through QCMP. `kind` is either `valid`, `invalid`, or `unsupported`.
* `quilkin_service_qcmp_ingress_latency_seconds`
The time from when the client created the packet, to when QCMP received it.
> feat(qcmp): add metrics to server.

- src/cli/service.rs
- src/main.rs
This adds a block of code on linux to invoke `io_uring_setup` to detect if it fails, the most likely reason of which inside containers would be seccomp profiles not allowing the syscall. Failing here means we can give a better error message and fail more gracefully, unlike in #1183 where a panic occurs inside tokio that almost completely hides the true error.
Related: #1183
> Explicitly fail if io_uring can't be setup

- crates/test/tests/xdp.rs
- src/net/cluster.rs
The `ClusterMap::remove_endpoint` and `ClusterMap::remove_endpoint_if` would 100% cause a deadlock if the last gameserver was removed from the locality as a reference was held via the clustermap iterator, while map.remove() was called. This just moves the locality removal outside of the iteration to avoid it.
> Fix ClusterMap deadlock

- benches/shared.rs
- crates/test/src/lib.rs
- src/cli.rs
- src/components/proxy.rs
- src/lib.rs
- src/net/phoenix.rs
- src/service.rs
This is just to separate service from being part of CLI, as the service configuration can come from many places. No actual API changes aside from that.
> chore(refactor): move service to the top level directory

- src/net/io/nic/xdp/process.rs
> fix(xdp): canonise IP address in process_client_packet

- src/providers.rs
The providers JoinSet was terminating early because of the mmdb provider completing. Updated so it now goes into pending.
> fix(mmdb): do not terminate task on completion

- crates/xds/src/client.rs
- src/metrics.rs
- src/net/sessions/inner_metrics.rs
- src/providers.rs
Also remove `ip_prefix` label from metrics for now due to high cardinality, we can come back to that later when needed. And add a `provider_task_failures_total` metric to track how often tasks fail.
> Don't fail xDS task on failed send_response

- benches/shared.rs
- crates/test/src/lib.rs
- crates/test/tests/proxy.rs
- src/cli.rs
- src/config.rs
- src/config/serialization.rs
- src/providers.rs
- src/providers/fs.rs
- src/service.rs
- src/test.rs
- tests/health.rs
- tests/metrics.rs
- tests/qcmp.rs
Part four of breaking up https://github.com/googleforgames/quilkin/pull/1245
Removes the `Default` implementation for Config and adds a constructor instead. Now the typemap will be initialized only with the types which are required by the providers/services that are enabled.
Also consolidates service id configuration so it is fetched from the cli struct and can be set with `--service.id` and not only `QUILKIN_SERVICE_ID`
> refactor: Remove Config::default(), init typemap depending on enabled services/providers

- src/codec/qcmp.rs
- src/metrics.rs
- src/net/phoenix.rs
* Remove the `error_estimate` label from the `phoenix_distance` metric and create a new gauge `phoenix_error_estimate` for it
* Add `phoenix_measurement_seconds` histogram to get visibility of the raw input samples into the phoenix system
* Remove the `asn` label from all `qcmp_*` metrics. Currently of little use but contributes a lot to cardinality.
> Phoenix metric improvements

- .github/workflows/image.yml
- image/Dockerfile.ghaction
Just the bare minimum to build the same container image that we got from cloud build via a github action and push it to `ghcr.io/embarkstudios/quilkin`. I've bypassed `build/Makefile` entirely and only picked out the relevant steps, but leaving all the old stuff as is for now. I created a new `Dockerfile.ghaction` that runs some of the old make targets in a dockerfile multi stage build instead as that works better with `docker/build-push-action`.
The `build-env` image is not saved in a remote registry but should be cached between runs in the gha cache.
The action should now run on
* any push to main
* any new tag (without `/` in the name)
* triggering the workflow manually (can't test this until the workflow is on main)
One image pushed so far: …
> Build container image with github actions

- crates/xds/src/client.rs
- src/config.rs
Because we were using different values for `XdsResource.name` and the first parameter to the `client_state.version_matches()` call we would always think that the version does not match and push an update.
Also make sure we check the version when propagating self.
This exposed a bug where if the relay restarts, a proxy would get stuck in unhealthy because the xDS client would only move back to healthy if it received an update, but since the unnecessary updates were removed we would not get one if nothing had changed.
> Ensure Datacenter xDS resource names and versions are consistent

- crates/xds/src/config.rs
- crates/xds/src/server.rs
- src/config.rs
- src/net/cluster.rs
This changes behavior so that we won't remove all resources that were added by a given agent from the relay Config when that agent disconnects gracefully. This could be disrupting in the usual case where the agent disconnects simply due to a rollout or rescheduling event.
The LocalVersion struct exits scope when the connection is closed so we don't need to clear the local state it has either.
Since the Cluster (EndpointSet) resource is versioned deterministically by hashing the endpoints, and updated as a batch, we don't have to worry about old endpoints lingering if we miss an update when one agent shuts down before another picks up.
In the case of the Datacenter resource this is handled separately through the `client_disconnected()` method on the `Configuration` trait, which in the case …
> Remove `LocalVersions.clear()`

- .github/workflows/image.yml
Since the package version got set to `version.workspace = true` we're now getting images tagged with `:workspace-true-<commit>`
> Use correct package version when tagging container image
