- README.md
The announcements have some great context, and they are nice credits to the founding teams - so let's add them to our README 🙂
> Add announcements to the README

- CODEOWNERS
So that we get pinged when PRs are up for review
> Add github CODEOWNERS file

- src/xds/ads_client.rs
If we hit connectivity issues, make sure we retry until
the server comes back up.
> Always backoff and retry management server

- CHANGELOG.md
- Cargo.toml
- README.md
- macros/Cargo.toml
Updates for the 0.2.0 release 🥳
Work on #398
> Release 0.2.0

- Cargo.toml
- build/templates/release-issue.md
- macros/Cargo.toml
Update items for 0.3.0 development.
Also made a small typo fix to the release template while I was in there.
Closes #398
> Preparation for 0.3.0

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Three templates:
1. Bug report template
2. Feature request template
3. Pull request template
Lifted these from Agones, and tweaked to adjust for this project.
Feedback definitely welcome!
> GitHub: Issue and PR templates

- docs/src/filters.md
- src/filters/capture_bytes.rs
- src/filters/chain.rs
- src/filters/read.rs
- src/filters/token_router.rs
- src/filters/write.rs
- src/metadata.rs
- src/test_utils.rs
> Add `metadata::Value`

- docs/src/proxy.md
- src/filters/chain.rs
- src/filters/firewall/metrics.rs
- src/metrics.rs
- src/proxy/server.rs
- src/proxy/server/metrics.rs
- src/proxy/sessions.rs
- src/proxy/sessions/session.rs
- src/proxy/sessions/session_manager.rs
>
> /kind bug
/kind feature
> /kind hotfix
* Added processing time histogram into proxy metrics.
* Moved event label keys and values into centralised const.
* Renamed Packer to UpstreamPacket
* Create DownstreamPacket struct
* Added SessionArg to Session constructor
* Updating documentation.
Work on #292
> Metric: Total Packet processing time

- docs/src/filters/writing_custom_filters.md
>
> /kind bug
> /kind hotfix
Added a section to "Writing Custom Filters" on the conventions used when naming filters.
Seemed like the most appropriate place for it, I couldn't think of anywhere better.
Comment on #454
N/A
> Document Filter naming conventions

- image/archive_dependencies.sh
>
> /kind bug
/kind cleanup
> /kind hotfix
Since we are no longer using this library, we no longer need to capture its source with the distributed container image.
N/A
I've left the script in place in case we end up needing to capture source at a later date for MPL, GPL, LGPL, or CDDL dependencies.
> Remove `slog-json` from archive_dependencies.sh

- build/build-image/Dockerfile
>
/kind bug
> /kind hotfix
My PR on htmltest got merged, so the branch was deleted. They
still haven't done a release, so we still need to clone and build.
Unblocks CI.
N/A
N/A
> Update htmltest for test-docs

- docs/src/filters/match.md
- src/filters/match.rs
- src/filters/match/metrics.rs
>
> /kind bug
/kind feature
> /kind hotfix
Implements metric counters for matched and fallthrough packets.
Closes #453
N/A
> Metrics for Match Filter

- docs/src/xds.md
Old one currently 404's blocking CI.
> Update link to DiscoveryRequest

- src/test_utils.rs
>
> /kind bug
/kind feature
> /kind hotfix
Wrote a little function to enable `tracing` logging safely, since you can only enable it once, so one can call this function across multiple tests without causing a panic.
Useful for debugging test failures.
Uden when debugging work on #410 
N/A
> Test Utility to enable tracing logging.

- .dockerignore
- build/Makefile
- build/README.md
- image/Dockerfile
>
> /kind bug
/kind feature
> /kind hotfix
Sometimes it's just faster and easier to build locally and create images and binaries that way, rather than use the build image.
Work on #553
This could potentially be extended to running tests as well, but limited it to building artifacts for now.
> Add BUILD_LOCAL to build tools

- docs/src/proxy-configuration.md
>
> /kind bug
> /kind hotfix
Update the configuration reference docs to include `clusters` and `localities`.
Also cleans up a few smaller issues in the current reference that I found.
Work on #546
At some point we should find a better way to represent this reference, but this will do for now.
> Update configuration reference docs

- examples/agones-xonotic/client-compress.yaml
- examples/agones-xonotic/sidecar-compress.yaml
- examples/agones-xonotic/sidecar.yaml
- examples/control-plane.yaml
- examples/iperf3/Dockerfile
- examples/iperf3/proxy.yaml
- examples/proxy.yaml
>
> /kind bug
/kind cleanup
> /kind hotfix
Updates for core examples, agones-xonotic, and iperf3 to new configuration format.
Work on #559
Still need to do the custom quilkin-filter-example, but wanted to do that in conjunction with the documentation review and update.
To test this you will want to replace `image: us-docker.pkg.dev/quilkin/release/quilkin:0.4.0` with your latest development build, until we have done our 0.4.0 release.
> Update example configurations to new format

- src/config/slot.rs
This replaces the derived implementations with manual ones to relax the trait bounds on `Slot<T>`. This allows for example `Slot<T>` to implement `Default` even if `T` does not.
> Relax trait bounds for Default, Deserialize, and Serialize for Slot<T>

- docs/src/proxy.md
- examples/grafana-dashboards/dashboards/dashboard-gameservers.yaml
> Fix metric names in dashboard

- src/xds/server.rs
This prevents the cache from growing out of control.
> Use `TimedSizedCache`

- examples/grafana-dashboards/dashboards/dashboard-gameservers.yaml
>
/kind bug
> /kind hotfix
With all the renaming of the metrics, the example dashboard was broken.
This updates the queries such that it works again!
Work for #546
Noting that as part of #456 we'll need to update the metrics docs.
> Fixes for example Grafana dashboard

- docs/src/SUMMARY.md
- docs/src/filters.md
>
> /kind bug
/kind cleanup
> /kind hotfix
As soon as I hit merge on #627 I realised that the docs weren't linked and I missed it on review! 🤦🏻‍♂️
So here are the fixes!
N/A
N/A
> Connect Timestamp Filter to rest of documentation

- .github/workflows/docs.yml
- build/Makefile
- build/build-image/Dockerfile
- docs/book.toml
- docs/src/examples.md
- docs/src/faq.md
- docs/src/filters/writing_custom_filters.md
- docs/src/integrations.md
- docs/src/introduction.md
- docs/src/proxy-configuration.md
- docs/src/quickstart-agones-xonotic.md
- docs/src/quickstart-netcat.md
- docs/src/using.md
- docs/src/xds.md
>
> /kind bug
/kind feature
> /kind hotfix
* Added variables for {{QUILKIN_VERSION}} and {{GITHUB_REF_NAME}}
* Updated the documentation to use variables.
* Includes integration with Make and GitHub Actions.
Closes #609
Switched GitHub Action to ubuntu, since manually installing mdbook and mdbook-variables. Should also have more capacity for Ubuntu machines on GitHub Actions.
>  mdbook-variables for Documentation

- Cargo.toml
- macros/Cargo.toml
>
> /kind bug
/kind cleanup
> /kind hotfix
Bumping version numbers for the next 0.5.0 release.
Closes #647
N/A
> Bump version to 0.5.0-dev

- docs/src/proxy/filters/writing_custom_filters.md
> docs/src/proxy/filters/writing_custom_filters: fix port typo

- Cargo.toml
- agones/Cargo.toml
- build.rs
- build/Makefile
- build/darwin-builder/setup.sh
>
> /kind bug
/kind cleanup
> /kind hotfix
Implement `vendor-protoc` feature for if protoc is installed locally.
For `build-macos-binary` rather than vendor, since it fails to compile, install protoc from release.
N/A
Update to https://github.com/googleforgames/quilkin/pull/651 which should fix the issues with tests. Would love thoughts on the approach.
> Fix for #651 vendor-protoc feature

- src/cli/manage.rs
This PR adds a retry task to the provider task. It does get caught by the main retry task, but catching it here keeps the xDS server alive.
> Add retry for provider task

- Cargo.toml
- src/cli.rs
>
> /kind bug
/kind feature
> /kind hotfix
Added a --version flag.
N/A
N/A
> --version flag for binary

- CHANGELOG.md
- Cargo.toml
- README.md
- build/release/cloudbuild.yaml
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
* Release updates for 0.5.0
* Weird issue with changelog generator, so switched it for an older version, and now it's working fine 🤷🏻‍♂️ (at some point should probably switch to GitHub changelog generator).
Work on #669
N/A
> Release 0.5.0

- Cargo.toml
- build/templates/github-release.md
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
* Updating version values
* Updated the release template to remove the debug image.
Closes #669
N/A
> Updates for 0.6.0-dev

- .github/workflows/docs.yml
- build/build-image/Dockerfile
>
/kind bug
> /kind hotfix
The 0.2.1 release of mdbook-variabes unfortuantely doesn't compile, so pinning to version 0.2.0
This will unblock the docs deployment github action.
N/A
Issue filed: https://gitlab.com/tglman/mdbook-variables/-/issues/2
> Workaround for mdbook-variables

- src/xds/client.rs
Previously if the channel closed, it would cause a fatal error.
> Recover when stream channel breaks

- src/config/providers/k8s.rs
> `continue` rather than `return` upon receiving invalid gameserver

- src/xds/client.rs
An initial attempt at fixing #726
> Fix proxy not retrying from received xDS error

- src/config/providers/k8s.rs
- src/config/providers/k8s/agones.rs
> Find the endpoint to delete using partial information from the server in case some information is missing

- src/config/providers.rs
> Clamp provider retry delay to five minutes

- docs/src/services/relay.md
work on #725
>
> /kind bug
> /kind hotfix
Closes #
> Add experimental notification in the docs

- src/cluster.rs
- src/config/providers/k8s.rs
This is improvement on #729 as I noticed we weren't always catching every valid server to delete.
> Improve server delete logic

- src/cli/agent.rs
- src/config/providers/k8s/agones.rs
- src/protocol.rs
- src/utils/net.rs
- tests/qcmp.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
This fixes #744 so it passes tests, and does some other small cleanup. 
This includes:
* Dual stack UdpSocket
* Update Agent code to use Dual Stack Socket
* Fix shutdown channel in Agent test
* Upgrade to 50ms delay on ping test (sometimes failed for me after compilation at 10ms)
Also foundational work on #666.
Once this is merged, I can move on to using the DualStackLocalSocket throughout Quilkin, so we can finish #666.
Also, I …
> [PR/Fixes] Agent Service / Dual Stack Socket

- src/cli/proxy.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Cleanup on logging - moving this log to debug, as it is quite verbose on proxy shutdown.
N/A
N/A
> Move session expiry to debug logging.

- examples/agones-xonotic-sidecar/sidecar-compress.yaml
- examples/agones-xonotic-sidecar/sidecar.yaml
- examples/agones-xonotic-xds/client-token.yaml
- examples/agones-xonotic-xds/proxy-pool.yaml
- examples/agones-xonotic-xds/xds-control-plane.yaml
- examples/iperf3/proxy.yaml
- examples/iperf3/run.sh
>
> /kind bug
/kind cleanup
> /kind hotfix
Updates all examples to work with new default ports and changes to configuration options.
Work on #725
> Update examples to work with upcoming 0.6.0

- CHANGELOG.md
- Cargo.toml
- README.md
- build/release/README.md
- build/templates/release-issue.md
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
Changes for 0.6.0 release!
Work on #725
Snuck in some small tweaks for release process as well.
> Release 0.6.0

- Cargo.toml
- agones/helm.yaml
- agones/main.tf
>
> /kind bug
/kind cleanup
> /kind hotfix
The older version of Agones has some security updates that needed to be applied, so updating to the latest version to bring things up to date.
N/A
Removed some Agones features we don't need. Made it easier to install on our internal systems a well.
> Update Agones to 1.33.0

- agones/src/lib.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
The old version was a very old version of Alpine. Updating to update to most recent security fixes as this image hangs around after tests in the K8s cluster.
N/A
N/A
> Agones: Update simple-game-server image to latest

- .github/workflows/docs.yml
- build/build-image/Dockerfile
>
/kind bug
> /kind hotfix
This PR should fix both the development docs being updated, and also the daily rebuild of our build container images that are used in CI.
N/A
Also reported: https://gitlab.com/tglman/mdbook-variables/-/issues/3
> Fix: mdbook-variables failing on doc building.

- src/cluster.rs
- src/config.rs
- src/endpoint/locality.rs
Wanted to make sure this was working as expected, and added a couple of trait implementations to make writing the code easier.
> Add test for Cluster::merge

- docs/src/services/proxy/qcmp.md
- src/cli.rs
- src/cli/qcmp.rs
- src/protocol.rs
fixes #751 
I needed this for testing reachability, so I made it.
> Add `qcmp ping` command

- Cargo.toml
- deny.toml
- src/endpoint/address.rs
>
> /kind bug
/kind cleanup
> /kind hotfix
Resolves: https://rustsec.org/advisories/RUSTSEC-2023-0052
N/A
Unblock CI.
Also simplifies the types in address.rs.
> Security: Update trust-dns-resolver

- README.md
>
> /kind bug
/kind cleanup
> /kind hotfix
A small tweak to explain more of the "why", and less of the "what".
N/A
N/A
> README description update

- v0.5.0/book/using.html
>
/kind bug
> /kind hotfix
Fix 0.5.0 container image tag.
Work on #786
Backporting the doc fix
> [docs] Fix 0.5.0/using.html

- v0.6.0/book/installation.html
>
/kind bug
> /kind hotfix
Fix the container tag for the documentation.
Closes #786
Please ignore CI failing.
> [docs] Fix 0.6.0/installation.html

- examples/agones-xonotic-sidecar/sidecar-compress.yaml
- examples/agones-xonotic-sidecar/sidecar.yaml
- examples/agones-xonotic-xds/fleet.yaml
>
> /kind bug
/kind cleanup
> /kind hotfix
Updating the examples to use the latest Xonotic release.
N/A
N/A
> Update to the latest Xonotic release.

- examples/agones-xonotic-relay/README.md
- examples/agones-xonotic-relay/client-token.yaml
- examples/agones-xonotic-relay/fleet.yaml
- examples/agones-xonotic-relay/gameserverallocation.yaml
- examples/agones-xonotic-relay/proxy-pool.yaml
- examples/agones-xonotic-relay/relay-control-plane.yaml
>
> /kind bug
/kind feature
> /kind hotfix
Updated examples from #772 moved into their own separate PR, so that when #772 is submitted, link checks om the quickstart documentation will resolve correctly.
Work on #772
N/A
> Examples for relay configuration

- CHANGELOG.md
- Cargo.toml
- README.md
- docs/src/deployment/quickstarts/agones-xonotic-relay.md
- docs/src/deployment/quickstarts/agones-xonotic-xds.md
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
Version changes and updates for the 0.7.0 release.
Also included fix for a small typo in quickstarts.
Work on #822
Please also take a look at the draft 0.7.0 release at https://github.com/googleforgames/quilkin/releases and make any changes you think are appropriate.
> Release 0.7.0

- Cargo.toml
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
Moving versions up for the next release.
Closes #822
N/A
> Prep for 0.8.0

- src/config/providers.rs
/kind hotfix
Update max_delay to 2 sec, as discussed in #839 
Closes #839
> Update max_delay to 2 sec

- src/net/xds.rs
This might not fix the flaky tests but it should remove some of the noise.
> Update xds client

- src/cli/proxy.rs
- src/cli/proxy/sessions.rs
Found that when the CPU is under heavy usage, one of these unwraps fails, so I removed all of them.
> Remove unwraps from proxy::sessions

- Cargo.lock
- Cargo.toml
Also updates dependencies because why not.
> Change debug symbols profile release -> bench

- examples/quilkin-filter-example/src/main.rs
- src/cli.rs
- src/cli/admin.rs
- src/cli/agent.rs
- src/cli/manage.rs
- src/cli/proxy.rs
- src/cli/relay.rs
- src/config.rs
- src/config/watch.rs
- src/config/watch/fs.rs
- src/filters/chain.rs
- src/net/xds.rs
- src/net/xds/client.rs
- src/net/xds/resource.rs
- src/net/xds/server.rs
- src/test.rs
- tests/capture.rs
- tests/compress.rs
- tests/concatenate.rs
- tests/filter_order.rs
- tests/filters.rs
- tests/firewall.rs
- tests/load_balancer.rs
- tests/local_rate_limit.rs
- tests/match.rs
- tests/token_router.rs
These were drive by changes/fixes I made while working on #882 that were unrelated to that change itself, splitting out here to remove them from that PR to make it easier to review separately.
> Split out changes

- Cargo.lock
- Cargo.toml
- macros/Cargo.toml
>
> /kind bug
> /kind hotfix
/kind release
Bumping versions since the release is now done!
Closes #902
N/A
> Prep for 0.9.0-dev

- src/components/proxy.rs
- src/net/phoenix.rs
This is a pared down version of changes I made while investigating #918. Still completely unable to reproduce.
> Slight test improvements

- build/build-image/Dockerfile
- src/config/xds.rs
- src/net/xds/client.rs
- src/net/xds/server.rs
This was copied from the non-delta version, but results in a bug.
Resolves: #927
> Don't run `add_host_to_datacenter`

- crates/test/tests/mesh.rs
- src/net/cluster.rs
- src/net/xds.rs
This means non-proxies take a cost that they don't need, but keeps the code simpler.
Resolves: #959
Resolves: #958
> Always build token maps

- Cargo.lock
- crates/xds/src/client.rs
- crates/xds/src/metrics.rs
- crates/xds/src/server.rs
- docs/src/deployment/quickstarts/netcat.md
- src/components/agent.rs
- src/components/manage.rs
- src/components/proxy.rs
Delta has been out long enough
> Nuke non-delta streams

- .github/pull_request_template.md
- .github/workflows/label-pr.yml
>
> /kind bug
/kind cleanup
> /kind hotfix
Stealing this from Agones, this GitHub action will label PRs based on the PR template, to make life a bit easier when doing releases, as labels will already be applied (if the template is used).
N/A
Also removed the `/kind hotfix` since that never applied to this project anyway.
> Github: PR Labeler action

- build/Makefile
- build/README.md
- build/build-image/Dockerfile
- rust-toolchain.toml
- src/filters/registry.rs
- src/net/phoenix.rs
>
> /kind bug
/kind cleanup
I stared with documenting how to regenerate protos, and found a few things that were blocking release, and also was just broken.
So this PR includes:
* Documenting how to regenerate protos with `cargo` and `make`.
* `make` targets for generating protobuf
* Fixes and updates for build tooling for release.
* Updates to rust version - which aligns with the available darwin builder image tags.
* Replace `live-server` which broke as unmaintained with `browser-sync` which is also way better.
**Which issue(s) this PR …
> Build tooling updates and fixes.

- src/components.rs
- src/components/agent.rs
- src/components/manage.rs
- src/components/proxy.rs
- src/components/proxy/io_uring_shared.rs
- src/components/proxy/packet_router.rs
- src/components/proxy/packet_router/io_uring.rs
- src/components/proxy/packet_router/reference.rs
- src/components/proxy/sessions/io_uring.rs
- src/components/proxy/sessions/reference.rs
- src/components/relay.rs
- src/config/providers.rs
- src/config/providers/k8s.rs
- src/filters/capture/affix.rs
- src/filters/capture/regex.rs
- src/net/maxmind_db.rs
- src/net/phoenix.rs
- src/pool.rs
- src/time.rs
- src/xds.rs
>
> /kind bug
/kind cleanup
Working on the 0.9.0 release, and found a stack of files with missing Apache headers. This fixes that!
Blocker on #964
N/A
> Add Apache Headers to those that are missing

- Cargo.lock
- Cargo.toml
- src/alloc.rs
- src/alloc/metrics.rs
- src/alloc/tracking.rs
- src/cli.rs
- src/lib.rs
Also adds support for replacing the system allocator with mimalloc.
Closes: #984
> Add basic heap stats

- docs/src/deployment/admin.md
>
> /kind bug
Docs for #998
N/A
Should probably get this in before doing 0.9.0 release, so we have docs it in the released docs.
> Docs for Heap Allocation Metrics

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- build/templates/release-issue.md
- crates/quilkin-proto/Cargo.toml
- crates/xds/Cargo.toml
- src/config.rs
- src/filters/token_router.rs
- src/net.rs
- src/net/endpoint.rs
- src/xds.rs
>
/kind bug
Got stuck with this release, as we have new crates that also need to be published and I hadn't factored that into the new publishing steps.
This includes moving the `xds` crates to being `quilkin-xds` so there was less concern with crate name collisions.
🤞🏻 hopefully this is it!
Work on #964
> Unstick release 0.9.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/macros/Cargo.toml
- crates/quilkin-proto/Cargo.toml
- crates/xds/Cargo.toml
>
> /kind bug
/kind release
Snuck in a small change to the changelog as well that didn't get captured by the release process breaking.
Closes #964
> Preparation for 0.10.0

- build/templates/release-issue.md
- examples/agones-xonotic-relay/proxy-pool.yaml
- examples/agones-xonotic-relay/relay-control-plane.yaml
- examples/agones-xonotic-sidecar/sidecar-compress.yaml
- examples/agones-xonotic-sidecar/sidecar.yaml
- examples/agones-xonotic-xds/proxy-pool.yaml
- examples/agones-xonotic-xds/xds-control-plane.yaml
>
> /kind bug
/kind cleanup
Updated examples to use 0.9.0 release, and also manually tested them to ensure they were still working.
Also updated the release process to increment the versions in the examples at release time as well, so they don't fall so far behind in the future.
Closes #995
> Update Examples to 0.9.0

- src/filters.rs
- src/filters/set.rs
- src/filters/token_router.rs
- src/xds.rs
This just allows config that have it specified to come over to the latest version
> Add HashedTokenRouter back as alias for TokenRouter

- crates/test/tests/xdp.rs
- src/net/xdp/process.rs
This fixes a leak where the Umem would eventually run out of space for new packets when packets are dropped instead of modified and forwarded.
> Fix umem leak

- build/Makefile
- docs/htmltest.yaml
> Cleanup docs CI

- crates/xds/src/config.rs
I'm unable to repro #1140, so this just change from a plain unwrap to a panic message with details so I can actually have some idea of what is wrong.
> Add details to panic

- crates/xds/src/config.rs
This reverts commit 1069c2e405ba85e31e5ab909e00284348ac6d5e1.
> Revert "use control plane id rather than the local node identifier (#1157)"

- crates/agones/src/relay.rs
Attempt to replicate broken tonic streaming.
> Spawn multiple agents in agones tests

- src/components/proxy/error.rs
- src/components/proxy/packet_router.rs
- src/config.rs
/kind feature
Partly addresses https://github.com/googleforgames/quilkin/issues/320, but does not cover dropping packets with the source IP set to quilkin's external IP address.
Related to #320
> Drop packets from disallowed source IPs

- src/config/providers.rs
Previously was only being spawned in the older component.
> fix(mmdb): spawn mmdb provider in new API

- .github/workflows/ci.yml
- crates/quilkin-proto/src/generated/quilkin/relay/v1alpha1.rs
- crates/test/src/lib.rs
- crates/xds/src/client.rs
- crates/xds/src/lib.rs
- crates/xds/src/server.rs
- docs/src/services/xds/proto/index.md
- proto/quilkin/filters/match/v1alpha1/match.proto
- proto/quilkin/filters/pass/v1alpha1/pass.proto
- proto/quilkin/relay/v1alpha1/relay.proto
- src/components/proxy.rs
- src/providers.rs
- src/service.rs
> Combine xDS and mDS services

- src/cli.rs
/kind bug
Previously the main method would exit immediately if a message was sent on `shutdown_rx`, not leaving any time for session draining. Now the main thread will exit when the `service_task` returns, after it has been given the chance to drain sessions. If any of the provider tasks returns (due to a non-recoverable error), we will trigger a graceful shutdown and still wait for the service_task to complete.
Closes #1216
> fix: actually wait for sessions to drain during shutdown

- src/net/maxmind_db.rs
This previous change did not cover all the cases it seems https://github.com/googleforgames/quilkin/pull/1226
/kind bug
> Ensure all IPs are canonical in maxmind lookup

- crates/xds/src/client.rs
- src/providers.rs
After testing on this branch https://github.com/googleforgames/quilkin/pull/1240 I think I've found the reason why things would silently get into a broken state. We never `.await`ed the `JoinHandle` for the xDS tasks and therefore never caught any errors propagated with `?`, so the task would die but we would still be stuck on `std::future::pending().await`, instead of letting `Self::task()` retry the task.
I removed the `DeltaSubscription` struct for simplicity, I don't think we need the abort on drop now anyway?
> Propagate task errors properly so they can be retried

- crates/xds/src/client.rs
- crates/xds/src/metrics.rs
- crates/xds/src/server.rs
Part six of breaking up https://github.com/googleforgames/quilkin/pull/1245
> Add quilkin_xds_errors_total and quilkin_xds_actions_total metrics

- src/net/cluster.rs
Makes it easy to see at a glance that two quilkins have the same version of an endpoint set
> Add EndpointSet version to /config output
